package chat

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"net/http"
	"regexp"
	"slices"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"

	"github.com/google/uuid"

	"github.com/justrag/go-backend/internal/ai"
	"github.com/justrag/go-backend/internal/httputil"
	"github.com/justrag/go-backend/internal/logctx"
	"github.com/justrag/go-backend/internal/prompts"
	"github.com/justrag/go-backend/internal/promptsafety"
)

// StarterSource is what the starter questions of an empty chat are generated
// from (Store.StarterContext).
type StarterSource struct {
	KBName string
	Files  []StarterFile
}

// StarterFile is one ingested document of a KB.
type StarterFile struct {
	ID   string
	Name string
}

// FileExcerptReader reads one excerpt per file from the vector DB
// (*vector.ChunkService), preferring the table of preferredDim (the KB's
// current embedding dimension, 0 = unknown). Optional: without it the
// questions are generated from the file names alone.
type FileExcerptReader interface {
	FileExcerpts(ctx context.Context, kbID string, fileIDs []string, maxLen, preferredDim int) (map[string]string, error)
}

// WithFileExcerpts wires the excerpt reader behind the starter questions.
func WithFileExcerpts(r FileExcerptReader) HandlerOption {
	return func(h *Handler) { h.fileExcerpts = r }
}

const (
	starterQuestionCount    = 6
	starterDocLimit         = 12
	starterExcerptLen       = 600
	maxStarterQuestionRunes = 120

	starterCacheMaxEntries = 512
	starterCacheTTL        = time.Hour
	starterFailureTTL      = time.Minute
	starterGenerateTimeout = time.Minute
)

type starterQuestionsResponse struct {
	Questions []string `json:"questions"`
}

// StarterQuestions handles GET /api/kb/{id}/starter-questions?lang=de|en:
// questions to open an empty chat with, generated by the fast-tier model
// (model_tier_fast, else the KB chat model) from the KB's name and one
// excerpt per document. Behind the KB view chain and the dedicated
// "starter_questions" rate limiter. A KB without eligible documents, a deployment without a model,
// or a failed/empty generation answers 200 with an empty list — the client
// then shows its configured suggestions only. A failure to read the KB's
// documents is a 500.
func (h *Handler) StarterQuestions(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	parsed, err := uuid.Parse(r.PathValue("id"))
	if err != nil {
		httputil.WriteErrorCtx(ctx, w, http.StatusNotFound, "knowledge base not found")
		return
	}
	kbID := parsed.String()
	lang := requestLanguage(r.URL.Query().Get("lang"))
	reply := func(q []string) {
		if q == nil {
			q = []string{}
		}
		w.Header().Set("Cache-Control", "no-cache")
		httputil.WriteJSONCtx(ctx, w, http.StatusOK, starterQuestionsResponse{Questions: q})
	}

	if h.aiResolver == nil {
		reply(nil)
		return
	}
	src, err := h.store.StarterContext(ctx, kbID, starterDocLimit)
	if err != nil {
		logctx.From(ctx).Error("chat.starter_questions: load documents", "error", err, "kb_id", kbID)
		httputil.WriteErrorCtx(ctx, w, http.StatusInternalServerError, "failed to load starter questions")
		return
	}
	if len(src.Files) == 0 {
		reply(nil)
		return
	}

	// The resolved model is part of the key: changing model_tier_fast must
	// not keep serving the previous model's questions until the TTL ends.
	model := ChatModelTierFast(ctx, h.siteConfigReader)
	key := kbID + "|" + lang + "|" + model + "|" + starterFingerprint(src)
	questions, err := h.starterCache.get(ctx, key, func(lctx context.Context) (starterOutcome, error) {
		return h.generateStarterQuestions(lctx, kbID, lang, model, src)
	})
	switch {
	case err == nil, errors.Is(err, errStarterCachedFailure):
		// A cached failure was logged when it happened.
	case ctx.Err() != nil:
		return // client gone; nobody to answer
	default:
		logctx.From(ctx).Warn("chat.starter_questions: generate", "error", err, "kb_id", kbID)
	}
	reply(questions)
}

// generateStarterQuestions runs one generation: excerpts (best effort), the
// model call on model (the resolved fast tier; "" = KB chat model), then
// validation. Zero valid questions is a failure, so it is cached as one
// (briefly) rather than as an empty answer for an hour. Questions generated
// from file names alone because the excerpt read failed are marked degraded,
// so they too are cached only briefly.
func (h *Handler) generateStarterQuestions(ctx context.Context, kbID, lang, model string, src StarterSource) (starterOutcome, error) {
	var excerpts map[string]string
	degraded := false
	if h.fileExcerpts != nil {
		preferredDim := 0
		if cfg, err := h.aiResolver.Resolve(ctx, kbID); err == nil && cfg != nil {
			preferredDim = cfg.EmbeddingDimensions
		}
		ids := make([]string, len(src.Files))
		for i, f := range src.Files {
			ids[i] = f.ID
		}
		var err error
		if excerpts, err = h.fileExcerpts.FileExcerpts(ctx, kbID, ids, starterExcerptLen, preferredDim); err != nil {
			// File names alone still give usable questions.
			degraded = true
			logctx.From(ctx).Warn("chat.starter_questions: excerpts", "error", err, "kb_id", kbID)
		}
	}
	docs := make([]prompts.StarterDoc, len(src.Files))
	for i, f := range src.Files {
		docs[i] = prompts.StarterDoc{Name: f.Name, Excerpt: excerpts[f.ID]}
	}

	raw, err := ai.GenerateStarterQuestions(ctx, h.aiResolver, kbID, model, src.KBName, docs, lang, starterQuestionCount)
	if err != nil {
		return starterOutcome{}, fmt.Errorf("starter questions: generate: %w", err)
	}
	questions := validateStarterQuestions(raw, starterQuestionCount)
	if len(questions) == 0 {
		return starterOutcome{}, fmt.Errorf("starter questions: none of %d model suggestions passed validation", len(raw))
	}
	return starterOutcome{questions: questions, degraded: degraded}, nil
}

// starterFingerprint identifies the generator's input: the KB name and the
// sorted ids of the documents it is shown. Adding, removing or replacing a
// document, or renaming the KB, yields a new cache key.
func starterFingerprint(src StarterSource) string {
	ids := make([]string, len(src.Files))
	for i, f := range src.Files {
		ids[i] = f.ID
	}
	slices.Sort(ids)
	h := sha256.New()
	h.Write([]byte(src.KBName))
	for _, id := range ids {
		h.Write([]byte{0})
		h.Write([]byte(id))
	}
	return hex.EncodeToString(h.Sum(nil)[:16])
}

// starterURLRe matches anything link-shaped: a scheme ("https://",
// "ftp://"), "www." or "mailto:".
var starterURLRe = regexp.MustCompile(`(?i)\b[a-z][a-z0-9+.-]*://|\bwww\.|\bmailto:`)

// validateStarterQuestions keeps the model suggestions that are safe to show
// as one-click chat openers, in order, at most limit: trimmed, non-empty, at
// most maxStarterQuestionRunes runes, a single line (no control or line/
// paragraph separator characters), no links, nothing the prompt-injection
// heuristic flags, and no duplicates (compared case- and
// whitespace-insensitively).
func validateStarterQuestions(raw []string, limit int) []string {
	out := make([]string, 0, limit)
	seen := make(map[string]bool, len(raw))
	for _, q := range raw {
		if len(out) == limit {
			break
		}
		q = strings.TrimSpace(q)
		switch {
		case q == "",
			utf8.RuneCountInString(q) > maxStarterQuestionRunes,
			strings.ContainsFunc(q, isLineBreakOrControl),
			starterURLRe.MatchString(q),
			promptsafety.LooksLikeInstruction(q):
			continue
		}
		norm := strings.ToLower(strings.Join(strings.Fields(q), " "))
		if seen[norm] {
			continue
		}
		seen[norm] = true
		out = append(out, q)
	}
	return out
}

func isLineBreakOrControl(r rune) bool {
	return unicode.IsControl(r) || unicode.In(r, unicode.Zl, unicode.Zp)
}
