package vector

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
	"sync"
	"unicode/utf8"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/pgvector/pgvector-go"
	"golang.org/x/sync/errgroup"
)

// embeddingFormatBufPool recycles the byte buffer used to format pgvector
// literals on every search and insert. We can't pool a strings.Builder
// directly because Builder.Reset() sets the underlying buf to nil — the
// no-copy String() guarantee implies the buffer is owned by the returned
// string. A raw []byte sidesteps that: we format into the buffer, copy it
// once into a string, and put the buffer back.
//
// Initial 72 KB covers the largest production embedding dimension (4096 ×
// up to ~16 bytes per float + brackets ≈ 65.5 KB). Sizing the cold pool
// to the worst case avoids the one-time re-allocation that a smaller
// starting capacity (16 KB) triggered on the first 4096-dim call per
// goroutine: see formatEmbedding's cap-check fallback below.
var embeddingFormatBufPool = sync.Pool{
	New: func() any { b := make([]byte, 0, 72*1024); return &b },
}

// ChunkInput holds the data needed to insert a single document chunk into the vector store.
type ChunkInput struct {
	Content string
	// ContextualPrefix is an optional Anthropic-style chunk-context prefix
	// (~50–100 tokens) generated by the LLM during ingestion. Stored in its
	// own column so the original Content can be returned to the user
	// verbatim, while the prefix is folded into the BM25 tsvector and the
	// embedding input upstream.
	ContextualPrefix string
	ContentHash      string // sha256 hex of normalized content; empty for empty content
	Embedding        []float64
	KbID             string
	FileID           string
	Metadata         map[string]any // serialized as JSONB
	// ParentChunkID is the FK to document_chunk_parents.id when this row
	// is a child chunk in the Phase 3 §D parent-child path. Nil for
	// legacy flat chunks (the column is nullable). Set by the processor
	// after AddParentChunks returns the parent IDs.
	ParentChunkID *string
	// NodeKind is "leaf" for regular chunks and "summary" for Phase F
	// RAPTOR-built summary nodes. Empty == "leaf"; the SQL column
	// DEFAULT covers callers that don't populate this field. Set by
	// internal/processor/raptor.Builder on summary inserts.
	NodeKind string
	// TreeLevel is 0 for leaves, 1..N for RAPTOR summary levels.
	// Surfaced in the answer prompt via renderSourceHeader and used by
	// the eval-only NodeKindFilter SQL clause.
	TreeLevel int
	// RaptorParentID is the in-table FK to the parent summary's id when
	// this row sits inside a RAPTOR tree. NULL on roots and on leaves
	// until the builder back-patches them via SetRaptorParent.
	RaptorParentID *string
}

// ChunkService provides CRUD operations for document chunks in the pgvector store.
type ChunkService struct {
	vectorDB *pgxpool.Pool
	// ensured caches dimensions for which the corresponding chunk table has
	// already been ensured in this process, so we only pay the DDL cost once
	// per dimension per process. DDL itself is idempotent, so concurrent
	// misses racing to ensure the same dim are harmless.
	ensured sync.Map
}

// NewChunkService creates a new ChunkService backed by the given connection pool.
func NewChunkService(vectorDB *pgxpool.Pool) *ChunkService {
	return &ChunkService{vectorDB: vectorDB}
}

// ensureTable guarantees the dimension-versioned chunk table exists before
// we insert into it. Closes the gap where an operator configures a new
// embedding dimension in the admin UI without restarting the worker (which
// would otherwise miss the boot-time EnsureVectorTables call).
func (s *ChunkService) ensureTable(ctx context.Context, dimensions int) error {
	if _, ok := s.ensured.Load(dimensions); ok {
		return nil
	}
	if err := EnsureChunkTable(ctx, PgxpoolExec{Pool: s.vectorDB}, dimensions); err != nil {
		return err
	}
	s.ensured.Store(dimensions, struct{}{})
	return nil
}

// formatEmbedding writes a []float64 as a pgvector literal "[1.0,2.0,3.0]"
// without going through json.Marshal (avoids reflection and extra
// allocations). On the search path this runs once per query; on the insert
// path it runs once per chunk in a tight loop. The format buffer comes from
// a sync.Pool so back-to-back calls reuse the same backing storage.
//
// bitSize=32 in AppendFloat: every embedding provider in this codebase
// (OpenAI, Cohere, BGE, vLLM) returns 32-bit floats over the wire that JSON
// decodes into float64 with trailing zero precision; emitting at float32
// precision is round-trip lossless for that data and skips the expensive
// shortest-round-trip search inside FormatFloat at full float64 precision.
func formatEmbedding(v []float64) string {
	bufPtr := embeddingFormatBufPool.Get().(*[]byte)
	buf := (*bufPtr)[:0]
	if cap(buf) < len(v)*16+2 {
		buf = make([]byte, 0, len(v)*16+2)
	}
	buf = append(buf, '[')
	for i, f := range v {
		if i > 0 {
			buf = append(buf, ',')
		}
		buf = strconv.AppendFloat(buf, f, 'g', -1, 32)
	}
	buf = append(buf, ']')
	out := string(buf)
	*bufPtr = buf
	embeddingFormatBufPool.Put(bufPtr)
	return out
}

// vectorArg wraps a float64 embedding as a pgvector.Vector for binding as a
// binary query parameter (see internal/database/pgvector_codec.go). pgvector
// columns are float4 on disk and formatEmbedding already emits at float32
// precision, so the float64→float32 narrowing here is bit-equivalent to the
// prior text path — identical stored bytes, ~4× smaller wire payload, and no
// per-component strconv formatting. When the codec is not registered on the
// connection, pgx falls back to pgvector.Vector's text Valuer, so this is
// safe regardless of registration.
func vectorArg(v []float64) pgvector.Vector {
	f := make([]float32, len(v))
	for i, x := range v {
		f[i] = float32(x)
	}
	return pgvector.NewVector(f)
}

// AddDocumentChunks batch-inserts chunks into the dynamic vector table for the given dimensions.
// Inserts are grouped in batches of 100 to avoid oversized queries.
//
// pgConfig is the Postgres text-search configuration (e.g. "german",
// "english", "simple") used to build the vector_index tsvector at INSERT
// time. Pass the value returned by PgTextSearchConfig(kbLanguage). An empty
// string falls back to "simple" so inserts never fail when the caller
// hasn't resolved a language yet.
func (s *ChunkService) AddDocumentChunks(ctx context.Context, fileID string, chunks []ChunkInput, dimensions int, pgConfig string) error {
	if len(chunks) == 0 {
		return nil
	}

	if err := s.ensureTable(ctx, dimensions); err != nil {
		return fmt.Errorf("ensure chunk table for %d dims: %w", dimensions, err)
	}

	if pgConfig == "" {
		pgConfig = "simple"
	}

	table := GetVectorTableName(dimensions)
	const batchSize = 100

	for start := 0; start < len(chunks); start += batchSize {
		end := start + batchSize
		if end > len(chunks) {
			end = len(chunks)
		}
		batch := chunks[start:end]

		if err := s.insertBatch(ctx, table, batch, pgConfig); err != nil {
			return fmt.Errorf("insert batch starting at %d: %w", start, err)
		}
	}

	return nil
}

// insertRowSQL is the per-row INSERT used by insertBatch. Each call queues
// this single statement into a pgx.Batch with its own 13-parameter argument
// list ($1..$12 are the row columns; $13 is the per-row regconfig).
//
// We use parameterized INSERT rather than COPY because pgvector's COPY binary
// protocol doesn't accept text-format vector literals, and the vector/halfvec
// column types need explicit casting that INSERT handles correctly.
//
// vector_index is computed inline as
//
//	to_tsvector($13::regconfig, COALESCE(contextual_prefix, '') || ' ' || content)
//
// so BM25/keyword search picks up the Anthropic-style contextual prefix when
// present. vector_index_simple uses the hardcoded 'simple' regconfig so the
// search-time OR-arm can match entity tokens that the language stemmer
// mangles (Krüger → krug, etc.) — same inputs, written once at INSERT time
// so neither arm relies on a separate backfill.
const insertRowSQLTemplate = `INSERT INTO "%s" (content, contextual_prefix, content_hash, embedding, embedding_low, kb_id, file_id, metadata, parent_chunk_id, node_kind, tree_level, raptor_parent_id, vector_index, vector_index_simple) VALUES ($1, $2, $3, $4::vector, $5::vector(256), $6::uuid, $7::uuid, $8::jsonb, $9::uuid, $10::text, $11::smallint, $12::uuid, to_tsvector($13::regconfig, COALESCE($2, '') || ' ' || $1), to_tsvector('simple', COALESCE($2, '') || ' ' || $1))`

// insertBatch pipelines a slice of ChunkInputs into the given table via
// pgx.Batch. Each row is its own INSERT, queued as a separate statement.
// SendBatch sends the whole batch in one round-trip; results are read per
// statement so failures report the offending chunk index instead of failing
// the entire batch opaquely.
//
// pgConfig is bound per row as $13 rather than shared across rows; binding
// per-row keeps every row's parameter list self-contained, which is what
// pgx.Batch expects (no inter-statement parameter dependencies).
func (s *ChunkService) insertBatch(ctx context.Context, table string, chunks []ChunkInput, pgConfig string) error {
	sqlStr := fmt.Sprintf(insertRowSQLTemplate, table)

	batch := &pgx.Batch{}
	for i, chunk := range chunks {
		// json.Marshal returns an owned []byte that we can hand straight to
		// batch.Queue. pgx retains the slice until SendBatch flushes, so
		// per-row metadata can't share a backing array — meaning any pool
		// would still force a copy on every iteration. Direct Marshal is
		// the same allocation count without the bytes.Buffer + json.Encoder
		// wrapper structs that the earlier pooled path created per row.
		metaBytes, err := json.Marshal(chunk.Metadata)
		if err != nil {
			return fmt.Errorf("chunk %d metadata: %w", i, err)
		}

		// Compute embedding_low from the full embedding deterministically.
		// L2NormalizeFirst256 returns nil for short or zero vectors; in
		// that case bind nil so the row still inserts (the chunk just
		// won't be considered by the two-pass scan; the full-dim path
		// still works for it).
		var embLowArg any
		if low := L2NormalizeFirst256(chunk.Embedding); low != nil {
			embLowArg = vectorArg(low)
		} else {
			embLowArg = nil
		}

		// Empty NodeKind binds 'leaf' explicitly (rather than relying on
		// the column DEFAULT) so the round-trip is the same regardless
		// of whether the caller set the field — keeps insert + read in
		// agreement when downstream code asserts on the string value.
		nodeKind := chunk.NodeKind
		if nodeKind == "" {
			nodeKind = "leaf"
		}

		batch.Queue(sqlStr,
			sanitizeUTF8(chunk.Content),
			nullableString(sanitizeUTF8(chunk.ContextualPrefix)),
			nullableString(chunk.ContentHash),
			vectorArg(chunk.Embedding),
			embLowArg,
			chunk.KbID,
			chunk.FileID,
			metaBytes,
			nullableUUIDString(chunk.ParentChunkID),
			nodeKind,
			chunk.TreeLevel,
			nullableUUIDString(chunk.RaptorParentID),
			pgConfig,
		)
	}

	br := s.vectorDB.SendBatch(ctx, batch)
	// Read every queued result before Close so any deferred error from a
	// later statement is observed (pgx requires draining the batch).
	var firstErr error
	for i := range chunks {
		if _, err := br.Exec(); err != nil && firstErr == nil {
			firstErr = fmt.Errorf("exec insert batch row %d (chunk_index=%d) into %q: %w", i, i, table, err)
		}
	}
	if closeErr := br.Close(); closeErr != nil && firstErr == nil {
		firstErr = fmt.Errorf("close insert batch for %q: %w", table, closeErr)
	}
	return firstErr
}

// sanitizeUTF8 replaces invalid UTF-8 byte sequences (e.g. Latin-1 0xa0
// non-breaking spaces from Confluence) with regular spaces so PostgreSQL
// accepts the content.
func sanitizeUTF8(s string) string {
	if utf8.ValidString(s) {
		return s
	}
	var b strings.Builder
	b.Grow(len(s))
	for i := 0; i < len(s); {
		r, size := utf8.DecodeRuneInString(s[i:])
		if r == utf8.RuneError && size == 1 {
			b.WriteByte(' ')
			i++
		} else {
			b.WriteRune(r)
			i += size
		}
	}
	return b.String()
}

// FileChunkRow is the minimal shape the AP-C1 KG-extraction stage
// reads from a chunk table: chunk id + content. ContextualPrefix is
// included so the extractor can fold prefix + content the same way
// the BM25 tsvector and embedder do — without it, structural chunks
// (team rows, attribute tables) lack the file-level context the LLM
// needs to identify entities.
type FileChunkRow struct {
	ID               string
	Content          string
	ContextualPrefix string
}

// GetChunksByFileID returns every chunk for the given (kb_id, file_id),
// ordered by created_at ASC (insertion order). Used by the KG
// extraction stage after AddDocumentChunks completes — the inserter
// doesn't return IDs, so we read them back. Cheap: one SELECT, btree
// index on file_id covers the predicate.
func (s *ChunkService) GetChunksByFileID(ctx context.Context, kbID, fileID string, dimensions int) ([]FileChunkRow, error) {
	table := GetVectorTableName(dimensions)
	// table comes from GetVectorTableName, never request data — same
	// invariant as DeleteChunksByFileID. Do NOT copy this Sprintf
	// shape with user-supplied values.
	query := fmt.Sprintf(`
		SELECT id::text, content, COALESCE(contextual_prefix, '')
		  FROM "%s"
		 WHERE kb_id = $1::uuid AND file_id = $2::uuid
		 ORDER BY created_at ASC
	`, table)
	rows, err := s.vectorDB.Query(ctx, query, kbID, fileID)
	if err != nil {
		return nil, fmt.Errorf("get chunks for file %s from %q: %w", fileID, table, err)
	}
	defer rows.Close()
	// Typical files produce 50–2000 chunks (RAPTOR descriptions cite
	// "≈31% extra rows on a 1000-chunk file"). 16 triggered ~6 doubling
	// events on 1000-chunk files; 256 covers the common case alloc-free
	// and only one doubling is needed for the long tail.
	out := make([]FileChunkRow, 0, 256)
	for rows.Next() {
		var r FileChunkRow
		if err := rows.Scan(&r.ID, &r.Content, &r.ContextualPrefix); err != nil {
			return nil, fmt.Errorf("scan chunk row: %w", err)
		}
		out = append(out, r)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate chunk rows: %w", err)
	}
	return out, nil
}

// DeleteChunksByFileID deletes all chunks belonging to a single file from the given dimension table.
func (s *ChunkService) DeleteChunksByFileID(ctx context.Context, fileID string, dimensions int) error {
	table := GetVectorTableName(dimensions)
	// table is derived from GetVectorTableName(dimensions) — formatted from
	// an integer, never user input. Do NOT copy this Sprintf pattern with
	// any value that could originate from a request.
	query := fmt.Sprintf(`DELETE FROM "%s" WHERE file_id = $1::uuid`, table)
	_, err := s.vectorDB.Exec(ctx, query, fileID)
	if err != nil {
		return fmt.Errorf("delete chunks for file %s from %q: %w", fileID, table, err)
	}
	return nil
}

// DeleteChunksByFileIDs deletes all chunks for a set of file IDs from the given dimension table.
func (s *ChunkService) DeleteChunksByFileIDs(ctx context.Context, fileIDs []string, dimensions int) error {
	if len(fileIDs) == 0 {
		return nil
	}
	table := GetVectorTableName(dimensions)
	// table is derived from GetVectorTableName(dimensions) — formatted from
	// an integer, never user input. Do NOT copy this Sprintf pattern with
	// any value that could originate from a request.
	query := fmt.Sprintf(`DELETE FROM "%s" WHERE file_id = ANY($1::uuid[])`, table)
	_, err := s.vectorDB.Exec(ctx, query, fileIDs)
	if err != nil {
		return fmt.Errorf("delete chunks for %d files from %q: %w", len(fileIDs), table, err)
	}
	return nil
}

// nullableString returns nil for an empty string so the column is NULL in
// Postgres rather than the empty string. Empty content_hash means "this chunk
// is too short to meaningfully dedupe".
func nullableString(s string) any {
	if s == "" {
		return nil
	}
	return s
}

// ListChunkTableDimensions returns the dimensions of every chunk table that
// currently exists in the vector DB, including 1536 for the legacy
// "document_chunks" table which is created by migration 0000 and therefore
// always present. Use this for bulk delete-across-all-dims operations
// instead of hardcoded dimension lists, which drift whenever an operator
// configures a new embedding model.
func (s *ChunkService) ListChunkTableDimensions(ctx context.Context) ([]int, error) {
	rows, err := s.vectorDB.Query(ctx,
		`SELECT tablename FROM pg_tables
		 WHERE schemaname = 'public' AND tablename ~ '^document_chunks_[0-9]+$'`)
	if err != nil {
		return nil, fmt.Errorf("list chunk tables: %w", err)
	}
	defer rows.Close()

	dims := []int{1536}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		var d int
		if _, err := fmt.Sscanf(name, "document_chunks_%d", &d); err == nil && d > 0 {
			dims = append(dims, d)
		}
	}
	return dims, rows.Err()
}

// DeleteChunksByFileIDAllDims deletes chunks for fileID from every existing
// chunk table in parallel. Each dim is a separate table so the DELETEs don't
// contend; len(dims) is small (typically 1-3, capped by the number of
// production embedding dimensions ever used on this deployment), so no
// concurrency cap is needed. errgroup returns the first error and cancels the
// rest — matches the previous "join all errors" intent closely enough: any
// failure means the caller must retry the whole fileID anyway, since a
// half-deleted file is the same problem either way.
func (s *ChunkService) DeleteChunksByFileIDAllDims(ctx context.Context, fileID string) error {
	dims, err := s.ListChunkTableDimensions(ctx)
	if err != nil {
		return err
	}
	g, gctx := errgroup.WithContext(ctx)
	for _, d := range dims {
		d := d
		g.Go(func() error {
			return s.DeleteChunksByFileID(gctx, fileID, d)
		})
	}
	return g.Wait()
}

// DeleteChunksByFileIDsAllDims deletes chunks for the given fileIDs from
// every existing chunk table in parallel. See DeleteChunksByFileIDAllDims
// for the concurrency rationale.
func (s *ChunkService) DeleteChunksByFileIDsAllDims(ctx context.Context, fileIDs []string) error {
	if len(fileIDs) == 0 {
		return nil
	}
	dims, err := s.ListChunkTableDimensions(ctx)
	if err != nil {
		return err
	}
	g, gctx := errgroup.WithContext(ctx)
	for _, d := range dims {
		d := d
		g.Go(func() error {
			return s.DeleteChunksByFileIDs(gctx, fileIDs, d)
		})
	}
	return g.Wait()
}

// RaptorLeafRow is one paginated leaf row needed by the RAPTOR builder:
// chunk id, content (for cluster-text concatenation), and the
// full-precision embedding (the clusterer's input). Defined in this
// package so the storage layer owns the row shape; the raptor package
// re-declares its own LeafRow with identical fields to avoid an
// internal/vector → internal/processor/raptor import cycle.
type RaptorLeafRow struct {
	ID        string
	Content   string
	Embedding []float64
}

// ListLeafEmbeddingsForRaptor returns every leaf chunk for (kb_id,
// file_id) in stable id order so the builder rebuilds the tree
// deterministically across re-ingests. Filtered to node_kind='leaf' so
// re-running the builder after a partial failure does NOT recursively
// feed previously-written summaries back into level 1.
//
// pageSize is reserved for a future streaming variant — the current
// implementation does the single SELECT. For typical files (≤ a few
// thousand chunks at 4096 dims) the result fits comfortably in memory.
func (s *ChunkService) ListLeafEmbeddingsForRaptor(ctx context.Context, kbID, fileID string, dimensions, pageSize int) ([]RaptorLeafRow, error) {
	_ = pageSize
	table := GetVectorTableName(dimensions)
	// table is derived from GetVectorTableName(dimensions) — formatted from
	// an integer, never user input. Do NOT copy this Sprintf pattern with
	// any value that could originate from a request.
	// embedding is scanned as a binary pgvector value (codec registered in
	// the pool's AfterConnect hook), not the `embedding::text` literal the
	// prior implementation parsed with strconv.ParseFloat per component —
	// 4096 parses per leaf row at full dim. pgx falls back to the text
	// Scanner when the codec is absent, so this is safe regardless.
	query := fmt.Sprintf(`
		SELECT id::text, content, embedding
		  FROM "%s"
		 WHERE kb_id = $1::uuid AND file_id = $2::uuid AND node_kind = 'leaf'
		 ORDER BY id`,
		table)
	rows, err := s.vectorDB.Query(ctx, query, kbID, fileID)
	if err != nil {
		return nil, fmt.Errorf("raptor list leaves: %w", err)
	}
	defer rows.Close()

	var out []RaptorLeafRow
	for rows.Next() {
		var r RaptorLeafRow
		var vec pgvector.Vector
		if err := rows.Scan(&r.ID, &r.Content, &vec); err != nil {
			return nil, fmt.Errorf("scan leaf row: %w", err)
		}
		// Downstream clustering operates on []float64; widen the float32
		// wire values (pgvector columns are float4 on disk, so this is
		// lossless relative to what was stored).
		f := vec.Slice()
		emb := make([]float64, len(f))
		for i, x := range f {
			emb[i] = float64(x)
		}
		r.Embedding = emb
		out = append(out, r)
	}
	return out, rows.Err()
}

// SetRaptorParent back-patches the raptor_parent_id column for the
// given child ids. Called once per cluster after the parent summary
// row has been inserted and its id is known. Idempotent — re-running
// with the same parent on rows that already point at it is a no-op.
func (s *ChunkService) SetRaptorParent(ctx context.Context, childIDs []string, parentID string, dimensions int) error {
	if len(childIDs) == 0 {
		return nil
	}
	table := GetVectorTableName(dimensions)
	// table is derived from GetVectorTableName(dimensions). See
	// invariant comment above.
	query := fmt.Sprintf(`UPDATE "%s" SET raptor_parent_id = $1::uuid WHERE id = ANY($2::uuid[])`, table)
	_, err := s.vectorDB.Exec(ctx, query, parentID, childIDs)
	if err != nil {
		return fmt.Errorf("raptor setparent: %w", err)
	}
	return nil
}

// LookupSummaryID returns the id of the most recently inserted summary
// row matching (kb_id, file_id, content, node_kind='summary'). The
// caller is the raptor adapter, which immediately follows
// AddDocumentChunks(one summary row) with this lookup to recover the
// generated id (AddDocumentChunks doesn't RETURN; duplicating its
// embedding_low/tsvector/dedup logic with a side INSERT-RETURNING
// variant is not worth it for the per-cluster summary path).
//
// Uniqueness is guaranteed within one (file, level) summary batch
// because clusters are content-disjoint and the adapter inserts one
// row at a time per cluster. ORDER BY created_at DESC + LIMIT 1
// defends against a future caller that inserts multiple summaries
// with the same content.
func (s *ChunkService) LookupSummaryID(ctx context.Context, kbID, fileID, content string, dimensions int) (string, error) {
	table := GetVectorTableName(dimensions)
	query := fmt.Sprintf(
		`SELECT id::text FROM "%s" WHERE kb_id=$1::uuid AND file_id=$2::uuid AND content=$3 AND node_kind='summary' ORDER BY created_at DESC LIMIT 1`,
		table,
	)
	var id string
	row := s.vectorDB.QueryRow(ctx, query, kbID, fileID, sanitizeUTF8(content))
	if err := row.Scan(&id); err != nil {
		return "", fmt.Errorf("lookup summary id: %w", err)
	}
	return id, nil
}

// GetRaptorDescendantLeafContents resolves every transitive leaf
// descendant of each summary id and returns a map keyed by the input
// summary id. The chat post-response citation validator uses this to
// extend its n-gram source-text for citations that point at a summary
// chunk: the summary's prose is paraphrased and may not match the
// answer text directly, but the underlying leaves typically contain
// the n-grams the validator looks for.
//
// Empty input returns nil, nil. Missing ids (summary deleted between
// search and validation) silently drop out of the result map — the
// validator's semantic-similarity fallback covers that case.
func (s *ChunkService) GetRaptorDescendantLeafContents(ctx context.Context, summaryIDs []string, dimensions int) (map[string][]string, error) {
	if len(summaryIDs) == 0 {
		return nil, nil
	}
	table := GetVectorTableName(dimensions)
	query := fmt.Sprintf(`
		WITH RECURSIVE descendants AS (
			SELECT id, id AS root_id, content, node_kind, raptor_parent_id
			  FROM "%s"
			 WHERE id = ANY($1::uuid[]) AND node_kind = 'summary'
			UNION ALL
			SELECT c.id, d.root_id, c.content, c.node_kind, c.raptor_parent_id
			  FROM "%s" c
			  JOIN descendants d ON c.raptor_parent_id = d.id
		)
		SELECT root_id::text, content FROM descendants WHERE node_kind = 'leaf'`,
		table, table,
	)
	rows, err := s.vectorDB.Query(ctx, query, summaryIDs)
	if err != nil {
		return nil, fmt.Errorf("raptor descendants: %w", err)
	}
	defer rows.Close()
	out := make(map[string][]string, len(summaryIDs))
	for rows.Next() {
		var root, content string
		if err := rows.Scan(&root, &content); err != nil {
			return nil, fmt.Errorf("scan descendant: %w", err)
		}
		out[root] = append(out[root], content)
	}
	return out, rows.Err()
}

// GetRaptorDescendantLeafContentsAcrossDims resolves summary
// descendants without the caller having to know which dim-keyed
// chunk table the summaries live in. Probes each existing dim's
// table and merges results. Used by the chat post-response path
// where threading the dimension through every orchestrator just
// for citation validation would be over-engineering — the
// per-request cost is one cheap SELECT per dim (typically 1-2 in
// production).
func (s *ChunkService) GetRaptorDescendantLeafContentsAcrossDims(ctx context.Context, summaryIDs []string) (map[string][]string, error) {
	if len(summaryIDs) == 0 {
		return nil, nil
	}
	dims, err := s.ListChunkTableDimensions(ctx)
	if err != nil {
		return nil, err
	}
	merged := make(map[string][]string, len(summaryIDs))
	for _, d := range dims {
		m, err := s.GetRaptorDescendantLeafContents(ctx, summaryIDs, d)
		if err != nil {
			// A missing column on a pre-0046 dim table surfaces here.
			// Log via the caller — return the error so they can decide.
			return merged, err
		}
		for k, v := range m {
			merged[k] = append(merged[k], v...)
		}
	}
	return merged, nil
}

// parseEmbeddingLiteral is the inverse of formatEmbedding: it parses
// pgvector's text format `[1.0,2.0,...]` into a []float64. Retained as the
// inverse of formatEmbedding and exercised by the round-trip test that guards
// formatEmbedding's text encoding (still used on the search / query-cache /
// longmem / HyPE paths). The RAPTOR reload now scans vectors as binary
// pgvector values directly (see ListLeafEmbeddingsForRaptor).
//
// Byte-scanning via strings.IndexByte instead of strings.Split avoids
// allocating an N-element string slice per vector.
func parseEmbeddingLiteral(s string) ([]float64, error) {
	if len(s) < 2 || s[0] != '[' || s[len(s)-1] != ']' {
		return nil, fmt.Errorf("not a pgvector literal: %q", s)
	}
	inner := s[1 : len(s)-1]
	if inner == "" {
		return []float64{}, nil
	}
	out := make([]float64, 0, 4096)
	for i := 0; len(inner) > 0; i++ {
		var part string
		if j := strings.IndexByte(inner, ','); j >= 0 {
			part = inner[:j]
			inner = inner[j+1:]
		} else {
			part = inner
			inner = ""
		}
		v, err := strconv.ParseFloat(strings.TrimSpace(part), 64)
		if err != nil {
			return nil, fmt.Errorf("parse component %d: %w", i, err)
		}
		out = append(out, v)
	}
	return out, nil
}

// DeleteChunksByKbID deletes all chunks belonging to a knowledge base from the given dimension table.
func (s *ChunkService) DeleteChunksByKbID(ctx context.Context, kbID string, dimensions int) error {
	table := GetVectorTableName(dimensions)
	query := fmt.Sprintf(`DELETE FROM "%s" WHERE kb_id = $1::uuid`, table)
	_, err := s.vectorDB.Exec(ctx, query, kbID)
	if err != nil {
		return fmt.Errorf("delete chunks for kb %s from %q: %w", kbID, table, err)
	}
	return nil
}
