package vector

import (
	"cmp"
	"context"
	"encoding/json"
	"fmt"
	"slices"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"go.opentelemetry.io/otel/attribute"
	"golang.org/x/sync/errgroup"
	"golang.org/x/sync/singleflight"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/justrag/go-backend/internal/ai"
	"github.com/justrag/go-backend/internal/logctx"
	"github.com/justrag/go-backend/internal/observability"
	"github.com/justrag/go-backend/internal/safego"
	"github.com/justrag/go-backend/internal/siteconfig"
)

// ---------------------------------------------------------------------------
// Per-operation timeouts
// ---------------------------------------------------------------------------
//
// The HTTP server's WriteTimeout caps the whole response (≥120 s for chat).
// Without per-op deadlines, a single stalled sidecar call (rerank, grader,
// embed) can hold the connection for the full server-wide budget. Each AI
// call below gets its own context.WithTimeout so the search pipeline fails
// fast when one stage degrades — letting the chat layer's fail-open paths
// (rerank skipped, CRAG fail-opens to "ambiguous", search returns empty)
// produce a usable answer instead of a connection-level timeout.
//
// Embed/rerank are the longest tail (cross-encoder over many docs); enhance
// (rewrite/expand/spell) and grade are short structured calls.
const (
	embedTimeout          = 30 * time.Second
	rerankTimeout         = 30 * time.Second
	enhanceQueryTimeout   = 15 * time.Second
	gradeRelevanceTimeout = 30 * time.Second
)

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

// SearchOptions controls optional pipeline stages for a Search call.
// LongContextTopK is the upper cap on the SearchResult chunk count
// when SearchOptions.LongContextMode is true. The chat layer applies
// its own token-budget truncation downstream, so this number only
// needs to be large enough to overflow any sensible budget (a 200-
// chunk pool at ~500 tokens each is already ~100 k tokens, the
// review's documented global-synthesis ceiling). Operators wanting
// a smaller / larger cap should adjust ChatLongContextMaxTokens,
// which gates the chat-side truncation; raising this constant
// without raising the budget just wastes the wider DB query.
const LongContextTopK = 200

type SearchOptions struct {
	Enhance    string            // "rewrite", "expand", "spell", or ""
	Filters    map[string]string // metadata filters (currently reserved for future use)
	FileIDs    []string          // restrict search to specific file IDs
	SkipCache  bool              // reserved for cache bypass
	HyDE       bool              // generate hypothetical answer before embedding
	MultiQuery bool              // generate alternative query phrasings in parallel
	// StepBack enables step-back retrieval: a single broader query is
	// generated by the LLM and run as an extra vector search whose results
	// fold into the RRF fusion stage. Plugs into the same `extraLists`
	// path as MultiQuery but generates a higher-level abstraction rather
	// than a paraphrase. The search code internally gates step-back on
	// QueryType == QueryTypeComplexReasoning, so setting StepBack on
	// other query types is a no-op (recorded as skipped_route).
	StepBack bool
	// Grade enables CRAG-style relevance grading after retrieval. When set,
	// the final returned chunks each carry a Grade and the result reports
	// how many of each verdict were seen. The grader runs on the trimmed
	// top-K result so it never wastes tokens on chunks that would be
	// filtered out anyway.
	Grade bool
	// GraderModel optionally pins the chat model used by the relevance
	// grader (typically a small/fast model). Empty = resolver default.
	GraderModel string
	// ModelOverride names an alternative chat model to use for auxiliary LLM
	// calls during retrieval (HyDE, MultiQuery). Empty = use resolver default.
	// Deep chat sets this to the configured enrichment model so its planning
	// calls go to a cheaper/faster model while the final answer stays on the
	// main chat model.
	ModelOverride string
	// QueryType classifies the query for downstream adaptive logic
	// (Phase 2 §A: per-query-type rerank_blend_alpha) and per-query-type
	// telemetry. Empty string is normalized to QueryTypeUnknown by the
	// search pipeline; callers should classify upstream when possible so
	// the label reflects the request as it entered the system.
	QueryType string
	// SubQueries is a caller-supplied list of additional queries to run as
	// parallel embedding searches and fold into RRF fusion via the same
	// extraLists path used by MultiQuery and StepBack. Non-empty SubQueries
	// is the Plan stage's signal that decomposition has already been done
	// upstream (RunPlanExecuteChat); when set, MultiQuery / StepBack / HyDE
	// should typically be left off by the caller to avoid double-fanout.
	//
	// Cap: caller is responsible for capping — no internal max here.
	// Each sub-query incurs one embedding call + one ANN search.
	SubQueries []string

	// GraphChunkIDs is a caller-supplied list of chunk IDs the AP-C4
	// graph router resolved from the KB's knowledge graph
	// (kg.Store.LookupSubgraph). When non-empty, the search service
	// fetches those chunks from the dim-keyed chunk table and folds
	// them into RRF via the same extraLists path used by SubQueries /
	// MultiQuery / StepBack. The graph contribution inherits the
	// vector RRF weight (no separate knob in v1).
	//
	// Cap: caller is responsible for capping (chat layer enforces
	// chat_graph_routing_max_chunks, default 15).
	GraphChunkIDs []string

	// HyPESearch enables the HyPE arm: the query embedding is matched
	// against ingest-time hypothetical-question embeddings in
	// chunk_hype_questions_<dim>; matched questions resolve to their
	// parent chunks, which fold into RRF via the same extraLists path as
	// GraphChunkIDs. No-op (fail-open) when the HyPE table is missing/empty.
	// Set by the chat layer from hype_search_enabled; never by users.
	HyPESearch bool

	// NodeKindFilter is the Phase F (RAPTOR) eval-only retrieval
	// filter. When non-empty (only "leaf" or "summary" are accepted),
	// the primary vector + keyword SELECTs add `AND node_kind = $N`
	// to the WHERE clause. Used by `./cmd/eval/eval --node-kind …`
	// to measure leaves-only vs. summary-included recall in
	// ablations. The public chat handler never sets this — production
	// retrieval always sees both kinds in one pool.
	NodeKindFilter string

	// LongContextMode is the T2-1 System-2 routing signal. When
	// true, Search() raises top-k to LongContextTopK (or the
	// admin-configured `chat_longcontext_top_k`), skips MMR, skips
	// score-drop filtering, and skips parent-child swap — every
	// operation whose purpose is to narrow the candidate pool. The
	// resulting wide chunk pool is what enables a long-context
	// answer pass (the chat layer is responsible for not over-
	// stuffing the model's window; see ChatLongContextMaxTokens).
	//
	// Set by the chat layer via ShouldRouteLongContext, never by
	// users. The query-time-only flag means a cached SearchResult
	// from normal-mode is NOT poisoned by long-context shape and
	// vice-versa (the shape hash differs).
	LongContextMode bool
}

// Query-type classification labels surfaced via Prometheus and structured
// logs. The set matches the eval harness's per-query-type breakdown so
// offline eval and production telemetry are directly comparable.
const (
	QueryTypeLookup           = "lookup"
	QueryTypeEnumeration      = "enumeration"
	QueryTypeComplexReasoning = "complex_reasoning"
	QueryTypeUnknown          = "unknown"
)

// SearchResult is the output of a Search call.
type SearchResult struct {
	Chunks            []SearchChunk `json:"chunks"`
	EnhancedQuery     string        `json:"enhancedQuery,omitempty"`
	FromCache         bool          `json:"fromCache,omitempty"`
	ContextWindowSize int           `json:"-"`
	TableName         string        `json:"-"`
	// Graded reports whether the relevance grader actually ran on this
	// result (controlled by SearchOptions.Grade). False when CRAG was
	// disabled or the grader silently failed open.
	Graded bool `json:"graded,omitempty"`
	// KeywordMatchFileIDs is the distinct set of file IDs that BM25
	// returned (in rank order). Used by downstream enumeration extraction
	// as pre-seeded candidates — BM25's exact-match signal anchors the
	// LLM's per-chunk yes/no decision against under-recall on templated
	// content where cross-encoder rerankers systematically downrank the
	// exact evidence chunks.
	KeywordMatchFileIDs []string `json:"-"`
}

// SearchChunk represents a single retrieved document chunk with scoring detail.
type SearchChunk struct {
	ID      string `json:"id"`
	Content string `json:"content"`
	// ContextualPrefix is the 1-sentence LLM-generated document-level context
	// attached to this chunk during ingestion (Anthropic-style Contextual
	// Retrieval). It's used for LLM prompt assembly — surfacing this to the
	// model turns an otherwise context-free chunk (e.g. a team list row)
	// into identifiable evidence ("... this passage lists the team of
	// project Alpha"). Empty when enrichment was disabled at ingestion.
	// Not persisted to the UI-facing MessageSource — the user still sees
	// the original content only.
	ContextualPrefix string         `json:"-"`
	FileID           string         `json:"fileId"`
	FileName         string         `json:"fileName"`
	Metadata         map[string]any `json:"metadata"`
	Score            float64        `json:"score"`
	VectorScore      float64        `json:"vectorScore,omitempty"`
	KeywordRank      float64        `json:"keywordRank,omitempty"`
	RerankScore      float64        `json:"rerank_score,omitempty"`
	// Grade is set by the CRAG-style relevance grader (see ai.GradeRelevance)
	// when SearchOptions.Grade is true. Empty when grading is disabled.
	Grade ai.Grade `json:"grade,omitempty"`
	// ParentChunkID is the FK to document_chunk_parents.id when this row
	// is a Phase 3 §D parent-child child chunk; nil for legacy flat rows.
	// The retrieval-time swap rewrites Content / ContextualPrefix from the
	// parent before this struct surfaces to chat-context assembly, so by
	// the time downstream code reads Content the swap is complete. The
	// field stays on the struct for ExpandNeighbors's NULL check and for
	// debugging / tracing.
	ParentChunkID *string `json:"-"`
	// NodeKind is "leaf" for ordinary chunks and "summary" for Phase F
	// RAPTOR-built summary nodes. Empty == "leaf". Surfaced to the
	// answer prompt via renderSourceHeader so the LLM knows the
	// snippet is paraphrased prose.
	NodeKind string `json:"nodeKind,omitempty"`
	// TreeLevel is 0 for leaves, 1..N for RAPTOR summaries.
	TreeLevel int `json:"treeLevel,omitempty"`
}

// ---------------------------------------------------------------------------
// SearchService
// ---------------------------------------------------------------------------

// SiteConfigReader reads individual site_configs values.
type SiteConfigReader interface {
	GetSiteConfigValue(ctx context.Context, key string) (*string, error)
}

// FeedbackReader supplies accumulated per-chunk feedback signals. Implemented
// by internal/feedback.Reader. Nil disables the retrieval feedback boost.
type FeedbackReader interface {
	NetSignals(ctx context.Context, kbID string, chunkIDs []string) (map[string]int, error)
}

// siteConfigBatchReader aliases the shared siteconfig.BatchReader. Single
// source of truth — see internal/siteconfig/reader.go. Test fakes satisfy
// only the single-key interface and fall through to the per-key path.
type siteConfigBatchReader = siteconfig.BatchReader

// Searcher is the contract callers depend on for hybrid retrieval. The
// concrete *SearchService satisfies it; consumers (chat orchestrators, MCP
// tools, eval harness, contentgen, publicapi, …) accept this interface so
// they can be tested with fakes that don't need a pgxpool. This is the
// canonical interface — package-local re-declarations should alias here.
//
// ExpandNeighbors is included even though most callers only need Search: it
// returns []SearchChunk (an exported type) instead of forcing the underlying
// NeighborFetcher contract on consumers, which uses an unexported row type.
type Searcher interface {
	Search(ctx context.Context, kbID, query string, limit int, opts SearchOptions) (*SearchResult, error)
	ExpandNeighbors(ctx context.Context, chunks []SearchChunk, windowSize int, tableName, kbID string) []SearchChunk
}

// Compile-time assertion that the production SearchService implements
// Searcher. Catches drift between the interface and its sole production
// implementation.
var _ Searcher = (*SearchService)(nil)

// SearchService orchestrates the hybrid search pipeline (vector + keyword,
// optional HyDE, optional multi-query, RRF fusion, optional reranking).
type SearchService struct {
	vectorDB       *pgxpool.Pool
	mainDB         *pgxpool.Pool
	aiResolver     *ai.ConfigResolver
	siteConfig     SiteConfigReader
	embeddingCache *ai.EmbeddingCache
	// chunkSvc is the parent-chunk lookup target for the Phase 3 §D
	// retrieval-time swap. Optional — when nil, the swap step is a no-op
	// and rows with non-nil ParentChunkID still surface their child
	// content (defensive fallback for tests / call sites that haven't
	// wired the dependency yet).
	chunkSvc *ChunkService
	// hype is the HyPEStore used for the query-time HyPE arm. When non-nil
	// and opts.HyPESearch is set, Search() matches the query embedding
	// against ingest-time hypothetical-question embeddings and folds the
	// resolved parent chunks into RRF via the extraLists path.
	hype *HyPEStore
	// queryCache is the optional semantic query-result cache. When non-nil
	// and enabled via site_config (`query_cache_enabled`), Search() consults
	// it before running the embed/search pipeline and stores the assembled
	// SearchResult on the success path. nil disables the feature with zero
	// overhead — the lookup-then-bypass block becomes a single field check.
	queryCache *QueryCache
	// rerankDefaultNoticeOnce gates a one-shot operator notice emitted the
	// first time a search runs with a reranker active AND no explicit
	// `rerank_blend_alpha` site_config entry. Pre-existing deployments had
	// an implicit 50/50 blend; the new default (1.0, pure reranker) is a
	// silent behaviour change for those, so we surface it at runtime.
	rerankDefaultNoticeOnce sync.Once
	// kbTableCache memoises kb_id → chunks-table-name for the AP-B1
	// keyword_search / chunk_read / document_outline tools. Defined in
	// keyword_search.go; declared here so the struct stays the
	// canonical "things SearchService owns" view.
	kbTableCache kbTableCache

	// siteConfigCache memoizes loadSiteConfig output for siteConfigCacheTTL.
	// Site config is global (no per-KB key) and only changes when an admin
	// edits the panel — fetching it on every Search wastes one DB round-trip
	// per request. The TTL is short enough that operator edits propagate
	// without an explicit invalidation step.
	//
	// atomic.Pointer (not RWMutex) because the cache is a single value read
	// on every Search call and refreshed at most once per TTL window. An
	// RWMutex still costs a CAS pair on RLock/RUnlock and bounces the lock's
	// cache line between cores under heavy concurrency; an atomic load is
	// wait-free and reads a single immutable snapshot. The refresh path uses
	// siteConfigSF to coalesce concurrent refresh attempts into one DB
	// round-trip per TTL window — singleflight (not a plain mutex) so the
	// losing goroutines block on a channel, the DB call isn't held under a
	// lock, and ctx cancellation on the in-flight loader propagates back to
	// waiters cleanly.
	siteConfigCache atomic.Pointer[siteConfigCacheEntry]
	siteConfigSF    singleflight.Group

	// kbLangCache memoizes per-KB language strings. KB language is set at KB
	// creation and effectively never changes; a long TTL is safe. Same
	// atomic.Pointer + singleflight pattern as siteConfigCache above: the
	// hot read is a wait-free atomic load + a map lookup, and concurrent
	// refreshers coalesce onto one DB round-trip per TTL window. The
	// snapshot loads every KB's language in one SELECT (the table is tiny
	// — typically O(10-100) rows), so per-KB lookups never touch the DB
	// in the steady state. KBs that landed after the last refresh fall
	// through to a single-row QueryRow without poisoning the snapshot;
	// the next TTL-driven refresh picks them up.
	kbLangCachePtr atomic.Pointer[kbLangSnapshot]
	kbLangSF       singleflight.Group

	feedback FeedbackReader // nil when the feedback loop is unwired/disabled
}

const (
	siteConfigCacheTTL = 10 * time.Second
	kbLangCacheTTL     = 10 * time.Minute
)

// kbLangSnapshot is the immutable per-KB language map handed to readers
// via atomic.Pointer. Built once per TTL window from a single SELECT.
type kbLangSnapshot struct {
	langs     map[string]string
	expiresAt time.Time
}

// siteConfigCacheEntry is the immutable snapshot stored in the atomic
// pointer. KBVectorConfig is a value type with no internal pointers, so
// snapshotting it once and handing readers a *const view is race-free
// without any locking on the read path.
type siteConfigCacheEntry struct {
	cfg       KBVectorConfig
	expiresAt time.Time
}

// Option configures a SearchService at construction time.
type Option func(*SearchService)

// WithEmbeddingCache attaches an EmbeddingCache so repeated queries skip the
// embedding API.
func WithEmbeddingCache(c *ai.EmbeddingCache) Option {
	return func(s *SearchService) { s.embeddingCache = c }
}

// WithSiteConfigReader attaches a SiteConfigReader so the search pipeline can
// load admin-tuned thresholds from the site_configs table.
func WithSiteConfigReader(r SiteConfigReader) Option {
	return func(s *SearchService) { s.siteConfig = r }
}

// SetFeedbackReader attaches the per-chunk feedback aggregate reader used by
// the retrieval-time boost. Safe to leave unset (boost stays off).
func (s *SearchService) SetFeedbackReader(fr FeedbackReader) { s.feedback = fr }

// WithChunkService attaches the ChunkService used for Phase 3 §D
// retrieval-time parent-content lookup. When omitted the parent swap is
// a no-op (legacy flat behaviour for rows with NULL parent_chunk_id is
// unaffected; rows with non-nil parent_chunk_id keep their child content
// in the LLM context — a soft degradation but never a search-time error).
func WithChunkService(c *ChunkService) Option {
	return func(s *SearchService) { s.chunkSvc = c }
}

// WithQueryCache attaches a QueryCache for semantic-similarity result
// reuse. Optional — when nil the search pipeline runs unchanged.
func WithQueryCache(qc *QueryCache) Option {
	return func(s *SearchService) { s.queryCache = qc }
}

// CloneWithSiteConfigReader returns a new SearchService that shares every
// backing dependency (DB pools, AI resolver, embedding/chunk/hype/query caches)
// but reads site_config through r instead of the original reader. The clone
// gets fresh sync primitives (sync.Once, singleflight.Group) and an empty
// config cache, so it is independent and race-free.
//
// Used by the chat handler to apply per-KB config overrides on a request-local
// instance without mutating the process-wide shared SearchService (mirrors the
// eval runner's private-SearchService pattern).
func (s *SearchService) CloneWithSiteConfigReader(r SiteConfigReader) *SearchService {
	return &SearchService{
		vectorDB:       s.vectorDB,
		mainDB:         s.mainDB,
		aiResolver:     s.aiResolver,
		siteConfig:     r,
		embeddingCache: s.embeddingCache,
		chunkSvc:       s.chunkSvc,
		hype:           s.hype,
		queryCache:     s.queryCache,
		// rerankDefaultNoticeOnce, kbTableCache, siteConfigCache, siteConfigSF,
		// kbLangCachePtr, kbLangSF: zero values — fresh, independent caches.
	}
}

// NewSearchService creates a SearchService backed by the given connection
// pools and AI config resolver. Production callers should pass both
// WithEmbeddingCache and WithSiteConfigReader; tests may omit them.
func NewSearchService(vectorDB, mainDB *pgxpool.Pool, aiResolver *ai.ConfigResolver, opts ...Option) *SearchService {
	s := &SearchService{
		vectorDB:   vectorDB,
		mainDB:     mainDB,
		aiResolver: aiResolver,
		hype:       NewHyPEStore(vectorDB),
	}
	for _, opt := range opts {
		opt(s)
	}
	return s
}

// InvalidateQueryCache nukes all query_cache entries for the given KB.
// Called by file-mutation paths (ingestion completion, file deletion,
// re-ingestion) to prevent serving stale cached results. No-op if the
// service was constructed without a QueryCache (the dependency is
// optional, so callers that don't have one wired pay nothing). Errors
// are returned to the caller; the cache is best-effort and the TTL
// fallback (24h default) eventually corrects any missed invalidation.
// ExpandNeighbors is a method-flavoured wrapper around the package-level
// ExpandNeighbors func so chat orchestrators can call it through the
// Searcher interface without leaking the unexported NeighborFetcher contract.
func (s *SearchService) ExpandNeighbors(ctx context.Context, chunks []SearchChunk, windowSize int, tableName, kbID string) []SearchChunk {
	return ExpandNeighbors(ctx, chunks, windowSize, s, tableName, kbID)
}

func (s *SearchService) InvalidateQueryCache(ctx context.Context, kbID string) error {
	if s.queryCache == nil {
		return nil
	}
	return s.queryCache.Invalidate(ctx, kbID)
}

// ---------------------------------------------------------------------------
// Search — main pipeline
// ---------------------------------------------------------------------------

// Search runs the hybrid search pipeline and returns ranked chunks.
//
// Pipeline stages:
//  1. Resolve KB config (language, thresholds, rerank model).
//  2. Optional query enhancement (rewrite / expand / spell-correct).
//  3. Optional HyDE: embed a hypothetical answer instead of the raw query.
//  4. Generate query embedding → derive table name and dimensions.
//  5. Vector search (cosine similarity, inside a transaction with ef_search hint).
//  6. Keyword search (full-text via tsvector; AND-required websearch_to_tsquery unioned with OR-of-tokens to_tsquery for the unquoted remainder when present, AND-required phraseto_tsquery for "..."-quoted phrases).
//  7. Optional multi-query: additional vector searches with alternative phrasings.
//  8. RRF fusion of all result lists.
//  9. File name lookup from the main DB.
//  10. Optional reranking + score blending.
//  11. Score filtering (min threshold + score-drop) when no reranker is used.
//  12. Deduplication (Jaccard similarity).
//  13. Trim to limit and return.
func (s *SearchService) Search(ctx context.Context, kbID, query string, limit int, opts SearchOptions) (*SearchResult, error) {
	ctx, span := observability.Tracer().Start(ctx, "rag.search")
	defer span.End()

	start := time.Now()
	// ------------------------------------------------------------------
	// 1. Resolve KB config
	// ------------------------------------------------------------------
	cfg, err := s.aiResolver.Resolve(ctx, kbID)
	if err != nil {
		return nil, fmt.Errorf("search: resolve config: %w", err)
	}

	// Resolve the KB's language (cached per-KB; KB language never changes
	// after creation so the long TTL is safe).
	lang := s.resolveKBLanguage(ctx, kbID)

	// Site config is global and only changes on admin edits — short TTL
	// cache eliminates the per-search DB round-trip without delaying
	// operator changes meaningfully.
	siteCfg := s.loadSiteConfigCached(ctx)
	pgConfig := PgTextSearchConfig(lang)

	// Apply configured default_top_k when the caller passes 0 (matches Node.js:
	// effectiveLimit = limit ?? config.defaultTopK). Per-query-type overrides
	// (TopNLookup / TopNEnumeration / TopNComplexReasoning) inherit DefaultTopK
	// when sentinel-zero. Empty / unknown query types always get DefaultTopK.
	if limit <= 0 {
		limit = EffectiveTopN(siteCfg, opts.QueryType)
	}
	// T2-1: Long-context mode raises the cap to LongContextTopK so
	// the wide pool reaches the chat-layer's token-budget cut. The
	// chat layer is responsible for the token budget (not the
	// chunk-count cap) — this number just guarantees Search hands
	// it enough chunks to fill that budget.
	if opts.LongContextMode && LongContextTopK > limit {
		limit = LongContextTopK
	}

	// searchLimit fetches more candidates than the caller wants so that RRF,
	// reranking, dedup, and filtering have enough material to work with.
	// When a reranker is active, fetch more (4x, min 50) to give it better material.
	var searchLimit int
	if cfg.RerankModel != "" {
		searchLimit = limit * 4
		if searchLimit < 50 {
			searchLimit = 50
		}
	} else {
		searchLimit = limit * 2
		if searchLimit < 30 {
			searchLimit = 30
		}
	}

	// ------------------------------------------------------------------
	// 0. Semantic query cache lookup (Feature 3 — see query_cache.go)
	// ------------------------------------------------------------------
	// Consult the QueryCache before running the embed/search pipeline. The
	// shape hash binds the cached result to the SearchOptions + resolved
	// limit, so two queries with the same text but different filters /
	// query types / top_n stay isolated. The query embedding doubles as the
	// cache lookup vector AND, on miss, will be reused by the main pipeline
	// — but the existing pipeline code re-encodes via ai.EncodeQuery (which
	// hits s.embeddingCache), so the second call is essentially free. The
	// embedding is cached at the EmbeddingCache layer regardless.
	qcCfg := loadQueryCacheConfig(ctx, s.siteConfig)
	var qcEmbedding []float64
	var qcHash []byte
	if s.queryCache != nil && qcCfg.enabled {
		emb, err := ai.EncodeQuery(ctx, s.aiResolver, query, siteCfg.QueryInstruction, kbID, s.embeddingCache)
		if err == nil && len(emb) > 0 {
			qcEmbedding = emb
			qcHash = shapeHash(opts, limit)
			// Per-query-type threshold: lookups can hit a looser threshold
			// because paraphrases of "what is X" reliably refer to the same
			// answer; complex_reasoning needs a tighter threshold because
			// slight rephrasings can flip the correct answer. Unknown /
			// unset query types inherit the base threshold.
			threshold := qcCfg.effectiveThreshold(opts.QueryType)
			if rj, hit, dist, lookupErr := s.queryCache.Lookup(ctx, kbID, qcHash, emb, threshold); lookupErr == nil && hit {
				var cachedResult SearchResult
				if uerr := json.Unmarshal(rj, &cachedResult); uerr == nil {
					tier := "semantic"
					if dist < 0.001 {
						tier = "exact"
					}
					observability.RecordQueryCacheHit(tier)
					logctx.From(ctx).Info("rag.query_cache.hit",
						"kb_id", kbID,
						"tier", tier,
						"cosine_distance", dist,
					)
					return &cachedResult, nil
				}
				logctx.From(ctx).Warn("query_cache: result_json deserialize failed; treating as miss")
			} else {
				observability.RecordQueryCacheMiss()
				logctx.From(ctx).Debug("rag.query_cache.miss", "kb_id", kbID, "nearest_distance", dist)
			}
		}
	}

	// ------------------------------------------------------------------
	// 2. Query enhancement
	// ------------------------------------------------------------------
	finalQuery := query
	// enhancedQuery is surfaced to the UI via result.EnhancedQuery; ONLY
	// explicit enhancement requests (rewrite / expand / spell) populate it.
	// Silent auto-spell-correct rewrites the internal finalQuery but does
	// NOT surface back to the user — "reformulated without me asking"
	// confuses users and a mid-range LLM's "spell correction" tends to
	// drift into paraphrase, not just typo fixes.
	var enhancedQuery string
	switch opts.Enhance {
	case "rewrite":
		enhanceCtx, cancel := context.WithTimeout(ctx, enhanceQueryTimeout)
		enhancedQuery, _ = ai.RewriteQuery(enhanceCtx, s.aiResolver, query, kbID, lang)
		cancel()
	case "expand":
		enhanceCtx, cancel := context.WithTimeout(ctx, enhanceQueryTimeout)
		enhancedQuery, _ = ai.ExpandQuery(enhanceCtx, s.aiResolver, query, kbID, lang)
		cancel()
	case "spell":
		enhanceCtx, cancel := context.WithTimeout(ctx, enhanceQueryTimeout)
		enhancedQuery, _ = ai.SpellCorrect(enhanceCtx, s.aiResolver, query, kbID, lang)
		cancel()
	default:
		// Silent auto-spell-correct: admin-configurable, off by default.
		// Uses the corrected text for search internally but does NOT set
		// enhancedQuery, so the UI renders the original user query
		// unchanged. Admins who explicitly want users to see corrections
		// should instruct them to pass enhance="spell".
		if siteCfg.AutoSpellCorrect {
			enhanceCtx, cancel := context.WithTimeout(ctx, enhanceQueryTimeout)
			corrected, err := ai.SpellCorrect(enhanceCtx, s.aiResolver, query, kbID, lang)
			cancel()
			if err == nil && corrected != "" {
				finalQuery = corrected
			}
		}
	}
	if enhancedQuery != "" {
		finalQuery = enhancedQuery
	}

	// ------------------------------------------------------------------
	// 3. HyDE — optionally embed a hypothetical answer
	// ------------------------------------------------------------------
	vectorSearchText := finalQuery
	if opts.HyDE {
		hydeCtx, cancelHyde := context.WithTimeout(ctx, enhanceQueryTimeout)
		hypo, err := ai.GenerateHypotheticalAnswerWithModel(hydeCtx, s.aiResolver, finalQuery, kbID, lang, opts.ModelOverride)
		cancelHyde()
		if err == nil && hypo != "" {
			vectorSearchText = hypo
		}
		// On failure we fall through to the normal query text.
	}

	// ------------------------------------------------------------------
	// 4. Generate query embedding (also tells us the dimensions)
	// ------------------------------------------------------------------
	// Asymmetric embedders (Qwen3-Embedding) want the query-side instruction
	// prefix; bare text for documents, wrapped text for queries. Empty
	// instruction falls through to GenerateEmbedding — safe for symmetric
	// models. Note: HyDE substitutes a hypothetical answer here, which is
	// document-like prose, so we intentionally still encode it as a query.
	// The instruction prefix nudges the vector toward the query manifold;
	// dropping it just for HyDE would split the cache/vector space in a way
	// that the retrained Qwen3 doesn't want.
	timer := newStageTimer(observability.RecordStageDuration)
	embedCtx, cancelEmbed := context.WithTimeout(ctx, embedTimeout)
	queryEmbedding, err := ai.EncodeQuery(embedCtx, s.aiResolver, vectorSearchText, siteCfg.QueryInstruction, kbID, s.embeddingCache)
	cancelEmbed()
	if err != nil {
		return nil, fmt.Errorf("search: generate embedding: %w", err)
	}
	dimensions := len(queryEmbedding)
	tableName := GetVectorTableName(dimensions)

	useHalfvec := dimensions > 2000 && dimensions <= 4000

	embeddingStr := formatEmbedding(queryEmbedding)

	// Pre-compute the low-dim query vector for MRL two-pass retrieval.
	// L2NormalizeFirst256 returns nil for short or zero embeddings; in
	// that case runVectorSearch's two-pass branch falls back to single-pass.
	var embeddingLowStr string
	if siteCfg.MRLTwoPass {
		if low := L2NormalizeFirst256(queryEmbedding); low != nil {
			embeddingLowStr = formatEmbedding(low)
		}
	}
	timer.Mark("embed")

	// ------------------------------------------------------------------
	// 5 & 6. Vector + keyword search
	// ------------------------------------------------------------------
	vectorResults, keywordResults, err := s.runPrimarySearches(
		ctx, tableName, embeddingStr, finalQuery, kbID, pgConfig,
		opts.FileIDs, searchLimit, dimensions, useHalfvec, siteCfg.HNSWEfSearch,
		siteCfg.MRLTwoPass, embeddingLowStr, siteCfg.BM25SimpleArmEnabled,
		siteCfg.BM25TieredBoost, opts.NodeKindFilter,
	)
	if err != nil {
		return nil, err
	}
	timer.Mark("primary_search")

	// Stage-by-stage retrieval telemetry. Each entry records the chunk
	// count and distinct file count observed AFTER the named pipeline
	// stage. A sudden drop between two consecutive stages pinpoints where
	// a recall problem originates (e.g. "4 relevant files at RRF → 2 at
	// MMR" means MMR is collapsing them). Kept compact: one structured
	// event per search, grep-friendly via `rag.search.stages`.
	// Shared scratch map reused across all per-stage file-count calls
	// below (RRF / rerank / score_filter / dedup / MMR / bm25_floor /
	// final + the two raw counts before that). clear() keeps the bucket
	// array on reuse so the 7+ counts per search land on the same
	// allocation instead of allocating a fresh map each call.
	filesScratch := make(map[string]struct{}, 64)
	countFilesRanked := func(docs []RankedDoc) int {
		clear(filesScratch)
		for _, d := range docs {
			if d.FileID != "" {
				filesScratch[d.FileID] = struct{}{}
			}
		}
		return len(filesScratch)
	}
	countFilesRaw := func(rows []rawRow) int {
		clear(filesScratch)
		for _, r := range rows {
			if r.FileID != "" {
				filesScratch[r.FileID] = struct{}{}
			}
		}
		return len(filesScratch)
	}
	// Pre-sized to fit every append below. Counted with the reranker path
	// active: initial 10 + stepback 2 + graph_inject 4 + rag_fusion 2 +
	// RRF 8 + rerank_alpha 2 + rerank 4 + score_filter 4 + dedup 4 + MMR 4 +
	// bm25_floor 2 + parent_swap 6 + final 24 = 76. 128 (next power-of-two)
	// avoids the cap=64 → 128 doubling that fired on every reranker-path
	// search.
	stageLog := make([]any, 0, 128)
	stageLog = append(stageLog,
		"stage", "search_stages",
		"vector_docs", len(vectorResults), "vector_files", countFilesRaw(vectorResults),
		"keyword_docs", len(keywordResults), "keyword_files", countFilesRaw(keywordResults),
		"top_n_route", routeLabelFor(opts.QueryType),
	)

	// ------------------------------------------------------------------
	// 7. Multi-query — additional vector searches in parallel
	// ------------------------------------------------------------------
	// extraLists carries vector-tier alt-query results. keywordExtraLists
	// carries the P4 RAG-Fusion BM25 arm per alt query when the
	// rag_fusion_enabled gate is on. Tracked separately so RRF weight
	// assembly applies RRFWeightVector to the former and RRFWeightBM25
	// to the latter (assembleRRFWeights).
	var extraLists [][]RankedDoc
	var keywordExtraLists [][]RankedDoc
	if opts.MultiQuery {
		mqCtx, cancelMQ := context.WithTimeout(ctx, enhanceQueryTimeout)
		altQueries, _ := ai.GenerateMultiQueriesWithModel(mqCtx, s.aiResolver, finalQuery, kbID, lang, opts.ModelOverride)
		cancelMQ()
		if len(altQueries) > 0 {
			extraLists = s.runMultiQuerySearches(
				ctx, tableName, altQueries, kbID, siteCfg.QueryInstruction,
				opts.FileIDs, searchLimit, dimensions, useHalfvec, siteCfg.HNSWEfSearch,
				siteCfg.MRLTwoPass,
			)
			if siteCfg.RAGFusionEnabled {
				bm25Lists := s.runMultiQueryBM25Searches(
					ctx, tableName, altQueries, kbID, pgConfig, opts.FileIDs, searchLimit, siteCfg.BM25SimpleArmEnabled, siteCfg.BM25TieredBoost,
				)
				keywordExtraLists = append(keywordExtraLists, bm25Lists...)
			}
		}
		timer.Mark("multi_query")
	}

	// ------------------------------------------------------------------
	// 7b. Step-back — one broader query, hardcoded to complex_reasoning
	// ------------------------------------------------------------------
	switch stepBackOutcome(opts.StepBack, opts.QueryType) {
	case "fired":
		sbCtx, cancelSB := context.WithTimeout(ctx, enhanceQueryTimeout)
		sbStart := time.Now()
		stepBackQuery, sbErr := ai.GenerateStepBackQueryWithModel(sbCtx, s.aiResolver, finalQuery, kbID, lang, opts.ModelOverride)
		cancelSB()
		observability.StepBackSeconds.Observe(time.Since(sbStart).Seconds())
		switch {
		case sbErr != nil:
			logctx.From(ctx).Warn("step-back: LLM failed",
				"error", sbErr,
				"duration_ms", time.Since(sbStart).Milliseconds(),
			)
			observability.RecordStepBackDecision("llm_error")
		case stepBackQuery == "":
			observability.RecordStepBackDecision("empty_output")
		default:
			observability.RecordStepBackDecision("fired")
			logctx.From(ctx).Info("rag.stepback.generated",
				"original_query", finalQuery,
				"stepback_query", stepBackQuery,
				"duration_ms", time.Since(sbStart).Milliseconds(),
			)
			sbLists := s.runMultiQuerySearches(
				ctx, tableName, []string{stepBackQuery}, kbID, siteCfg.QueryInstruction,
				opts.FileIDs, searchLimit, dimensions, useHalfvec, siteCfg.HNSWEfSearch,
				siteCfg.MRLTwoPass,
			)
			extraLists = append(extraLists, sbLists...)
			stageLog = append(stageLog, "stepback_lists", len(sbLists))
			if siteCfg.RAGFusionEnabled {
				sbBM25 := s.runMultiQueryBM25Searches(
					ctx, tableName, []string{stepBackQuery}, kbID, pgConfig, opts.FileIDs, searchLimit, siteCfg.BM25SimpleArmEnabled, siteCfg.BM25TieredBoost,
				)
				keywordExtraLists = append(keywordExtraLists, sbBM25...)
			}
		}
	case "skipped_route":
		observability.RecordStepBackDecision("skipped_route")
	case "skipped_disabled":
		observability.RecordStepBackDecision("skipped_disabled")
	}
	timer.Mark("step_back")

	// ------------------------------------------------------------------
	// 7c. SubQueries — caller-driven decomposed queries (Plan-and-Execute)
	// ------------------------------------------------------------------
	if len(opts.SubQueries) > 0 {
		subLists := s.runMultiQuerySearches(
			ctx, tableName, opts.SubQueries, kbID, siteCfg.QueryInstruction,
			opts.FileIDs, searchLimit, dimensions, useHalfvec, siteCfg.HNSWEfSearch,
			siteCfg.MRLTwoPass,
		)
		extraLists = append(extraLists, subLists...)
		logctx.From(ctx).Info("rag.search.subqueries",
			"count", len(opts.SubQueries),
			"lists_returned", len(subLists),
		)
		if siteCfg.RAGFusionEnabled {
			subBM25 := s.runMultiQueryBM25Searches(
				ctx, tableName, opts.SubQueries, kbID, pgConfig, opts.FileIDs, searchLimit, siteCfg.BM25SimpleArmEnabled, siteCfg.BM25TieredBoost,
			)
			keywordExtraLists = append(keywordExtraLists, subBM25...)
		}
	}
	timer.Mark("sub_queries")

	// ------------------------------------------------------------------
	// 7d. AP-C4 graph-router chunk injection
	// ------------------------------------------------------------------
	// Caller (chat layer) has already resolved entity → subgraph →
	// chunk IDs (chat.ResolveGraphChunks); here we just bulk-fetch
	// those chunks and append them as another extra list. Score=0 on
	// the rows because RRF takes rank position only — the graph
	// list's contribution is purely "these chunks were related to
	// the matched entity by the KB's knowledge graph".
	//
	// Failure mode: any DB error logs + records the fetch_failed
	// outcome and proceeds without injection (fail-open). The chat
	// turn must not fail because the KG fetch hiccupped.
	if len(opts.GraphChunkIDs) > 0 {
		graphRows, err := s.fetchChunksByIDs(ctx, tableName, kbID, opts.GraphChunkIDs)
		switch {
		case err != nil:
			observability.RecordGraphRoutingChunksInjected("fetch_failed", 0)
			logctx.From(ctx).Warn("rag.search.graph_inject_fetch_failed",
				"error", err, "requested", len(opts.GraphChunkIDs))
		case len(graphRows) == 0:
			observability.RecordGraphRoutingChunksInjected("no_chunks", 0)
		default:
			graphList := toRankedDocs(graphRows, true)
			extraLists = append(extraLists, graphList)
			observability.RecordGraphRoutingChunksInjected("fetched", len(graphRows))
			stageLog = append(stageLog,
				"graph_injected_chunks", len(graphRows),
				"graph_requested_chunks", len(opts.GraphChunkIDs),
			)
		}
	}
	timer.Mark("graph_inject")

	// ------------------------------------------------------------------
	// 7e. HyPE — hypothetical-question embedding arm
	// ------------------------------------------------------------------
	if opts.HyPESearch && s.hype != nil {
		hypeList := s.runHyPESearch(ctx, tableName, embeddingStr, kbID, opts.FileIDs, searchLimit, dimensions)
		if len(hypeList) > 0 {
			extraLists = append(extraLists, hypeList)
			stageLog = append(stageLog, "hype_injected_chunks", len(hypeList))
		}
	}
	timer.Mark("hype")

	// ------------------------------------------------------------------
	// 8. RRF fusion (weighted)
	// ------------------------------------------------------------------
	// List order matches assembleRRFWeights: [vector, keyword,
	// vec_extras..., kw_extras...]. Vector extras are alt-query
	// vector searches (multi-query / step-back / sub-queries / graph
	// injection); keyword extras are the P4 RAG-Fusion BM25 arm
	// per alt query. Each list group inherits its tier's weight.
	vectorDocs := toRankedDocs(vectorResults, true)
	keywordDocs := toRankedDocs(keywordResults, false)
	lists := make([][]RankedDoc, 0, 2+len(extraLists)+len(keywordExtraLists))
	lists = append(lists, vectorDocs, keywordDocs)
	lists = append(lists, extraLists...)
	lists = append(lists, keywordExtraLists...)
	weights := assembleRRFWeights(siteCfg, len(extraLists), len(keywordExtraLists))
	fused := FuseRRFWeighted(60, weights, lists...)
	if len(keywordExtraLists) > 0 {
		stageLog = append(stageLog, "rag_fusion_bm25_lists", len(keywordExtraLists))
	}
	stageLog = append(stageLog,
		"rrf_docs", len(fused), "rrf_files", countFilesRanked(fused),
		"rrf_weight_vector", siteCfg.RRFWeightVector,
		"rrf_weight_bm25", siteCfg.RRFWeightBM25,
	)
	timer.Mark("rrf")

	// ------------------------------------------------------------------
	// 9. File name lookup
	// ------------------------------------------------------------------
	fileNames, err := s.lookupFileNames(ctx, fused)
	if err != nil {
		// Non-fatal: proceed with empty names.
		fileNames = make(map[string]string)
	}

	// Per-search scratch maps (reranker score map + BM25-floor snapshot),
	// pooled to keep their bucket arrays warm across requests. Acquired here
	// (after the early-error returns above) so the deferred Put covers every
	// remaining exit path. clear() before each use drops the prior search's
	// entries; the snapshot is also cleared on Put to release its RankedDoc
	// references promptly.
	scratch := searchScratchPool.Get().(*searchScratch)
	defer func() {
		clear(scratch.snapshot)
		searchScratchPool.Put(scratch)
	}()

	// ------------------------------------------------------------------
	// 10. Reranking
	// ------------------------------------------------------------------
	useReranker := cfg.RerankModel != ""
	if useReranker {
		s.maybeLogRerankDefaultNotice(ctx)
		// Feed the reranker `prefix + "\n\n" + content` when the row carries
		// a contextual_prefix — same recipe the embedder and BM25 tsvector
		// use at INSERT time. Without this the reranker scores bare child /
		// chunk text and disagrees with the embedding/BM25 ranking on
		// entity-anchored lookup queries (the prefix is what disambiguates
		// "Frau Müller is the lead" from generic project-management
		// boilerplate). No-op for KBs without contextual enrichment
		// (prefixes are empty strings → bare content path is preserved).
		//
		// Concatenation goes through a pooled []byte buffer reused across
		// every doc in the loop: the per-doc `string(buf)` copy is still
		// required (the strings must be independent — the reranker keeps
		// references) but the intermediate `prefix + "\n\n" + content`
		// allocation is eliminated, which at 25 docs per search adds up
		// under load.
		docs := buildRerankDocs(fused)
		rerankCtx, cancelRerank := context.WithTimeout(ctx, rerankTimeout)
		rerankScores, err := ai.Rerank(rerankCtx, s.aiResolver, finalQuery, docs, kbID, 0, ai.RerankOptions{
			UseChatTemplate: siteCfg.RerankUseChatTemplate,
			Instruction:     siteCfg.RerankInstruction,
		})
		cancelRerank()
		if err == nil && len(rerankScores) > 0 {
			scoreMap := scratch.rerankScores
			clear(scoreMap)
			for _, rs := range rerankScores {
				scoreMap[rs.Index] = rs.Score
			}
			rerankStddev := ComputeRerankScoreStddev(scoreMap)
			observability.RecordRerankerHealth(rerankStddev)
			if rerankStddev < observability.RerankerDegenerateStddevThreshold {
				logctx.From(ctx).Warn("rag.reranker.degenerate",
					"stddev", rerankStddev,
					"threshold", observability.RerankerDegenerateStddevThreshold,
					"score_count", len(scoreMap),
					"hint", "calibration collapse — verify reranker model and vLLM pooling/runner mode",
				)
			}
			effectiveAlpha := EffectiveRerankAlphaForQuery(siteCfg, opts.QueryType, isEntityAskingQuery(finalQuery))
			// T2-4 dynamic alpha: shift the per-route base by the
			// BPE-rarity heuristic when enabled. Rare-token queries
			// (named entities, error codes) reduce α; common-token
			// queries raise it. baseAlpha (post-route-resolution) is
			// the input so the shift composes correctly with the
			// existing per-route / entity overrides.
			if siteCfg.HybridDynamicAlphaEnabled {
				shifted := PredictHybridAlpha(finalQuery, effectiveAlpha, siteCfg.HybridDynamicAlphaSensitivity)
				if shifted != effectiveAlpha {
					stageLog = append(stageLog, "rerank_alpha_base", effectiveAlpha)
					effectiveAlpha = shifted
				}
			}
			fused = BlendRerankScores(fused, scoreMap, effectiveAlpha)
			stageLog = append(stageLog, "rerank_alpha_effective", effectiveAlpha)
		}
		stageLog = append(stageLog, "rerank_docs", len(fused), "rerank_files", countFilesRanked(fused))
		timer.Mark("rerank")
	}

	// ------------------------------------------------------------------
	// 10b. Online feedback loop: nudge scores by accumulated thumbs
	// up/down on answers that cited each chunk. Gated; default off.
	// Fail-open — a feedback read error never fails the search.
	// ------------------------------------------------------------------
	if siteCfg.FeedbackBoostEnabled && s.feedback != nil && len(fused) > 0 {
		ids := make([]string, len(fused))
		for i := range fused {
			ids[i] = fused[i].ID
		}
		if net, err := s.feedback.NetSignals(ctx, kbID, ids); err != nil {
			logctx.From(ctx).Warn("feedback boost: net signals", "error", err, "kb_id", kbID)
		} else if len(net) > 0 {
			weight := siteCfg.FeedbackBoostWeight
			if weight <= 0 {
				weight = 0.05
			}
			ApplyFeedbackBoost(fused, net, weight)
			slices.SortStableFunc(fused, func(a, b RankedDoc) int { return cmp.Compare(b.Score, a.Score) })
			stageLog = append(stageLog, "feedback_boost_applied", len(net))
		}
	}

	// ------------------------------------------------------------------
	// 11. Score filtering (only when no reranker provides quality signal)
	// ------------------------------------------------------------------
	// T2-1: Long-context mode preserves the wide pool — score
	// filtering would re-narrow it to the conventional band, which
	// defeats the routing's whole purpose.
	if !useReranker && !opts.LongContextMode {
		if siteCfg.MinSimilarityThreshold > 0 {
			fused = ApplyMinThreshold(fused, siteCfg.MinSimilarityThreshold)
		}
		if siteCfg.ScoreDropThreshold > 0 {
			fused = ApplyScoreDrop(fused, siteCfg.ScoreDropThreshold)
		}
		stageLog = append(stageLog, "score_filter_docs", len(fused), "score_filter_files", countFilesRanked(fused))
		timer.Mark("score_filter")
	}

	// 11b. Reranker-active elbow cutoff (opt-in, default off). The block
	// above skips score filtering when a reranker ran — the blended,
	// normalized rerank score is the trusted signal — but a sharp gap in
	// that blended score still marks a natural relevance cliff. When the
	// operator opts in, cut the tail past the elbow on the post-rerank
	// list. Off by default so retrieval is byte-stable; long-context mode
	// is exempt (it deliberately keeps the wide pool).
	if useReranker && !opts.LongContextMode && siteCfg.RerankScoreDropEnabled && siteCfg.RerankScoreDropThreshold > 0 {
		before := len(fused)
		fused = ApplyScoreDrop(fused, siteCfg.RerankScoreDropThreshold)
		stageLog = append(stageLog, "rerank_score_drop_docs", len(fused), "rerank_score_drop_cut", before-len(fused))
		timer.Mark("rerank_score_drop")
	}

	// ------------------------------------------------------------------
	// 12. Deduplication
	// ------------------------------------------------------------------
	fused = Deduplicate(fused, 0.85)
	stageLog = append(stageLog, "dedup_docs", len(fused), "dedup_files", countFilesRanked(fused))
	timer.Mark("dedup")

	// Snapshot every post-dedup doc by ID so the BM25 floor (step 13b
	// below) can reinsert chunks MMR and trim may have dropped — with
	// their fully-scored `Score` field intact. Keyed on ID because the
	// same chunk can appear in both `fused` (post-blend Score) and
	// `keywordDocs` (raw BM25 rank in Score) — we want the blended entry
	// for downstream ranking / truncation.
	fusedSnapshot := scratch.snapshot
	clear(fusedSnapshot)
	for _, d := range fused {
		fusedSnapshot[d.ID] = d
	}

	// MMR diversity rerank. λ=1.0 short-circuits to current behaviour (pure
	// relevance). Pool is min(len(fused), limit*2).
	// T2-1: Long-context mode keeps the full pool — diversity
	// re-ranking against `limit` would re-narrow the result. The
	// chat layer expects the wide pool to flow through unmodified.
	if !opts.LongContextMode && len(fused) > limit {
		pool := limit * 2
		if pool > len(fused) {
			pool = len(fused)
		}
		fused = ApplyMMR(fused[:pool], siteCfg.MMRLambda, limit)
	}
	stageLog = append(stageLog, "mmr_docs", len(fused), "mmr_files", countFilesRanked(fused))
	timer.Mark("mmr")

	// ------------------------------------------------------------------
	// 13. Trim and convert to SearchChunk
	// ------------------------------------------------------------------
	if len(fused) > limit {
		fused = fused[:limit]
	}

	// 13b. BM25 floor — see ApplyBM25Floor.
	var bm25Reinserted int
	fused, bm25Reinserted = ApplyBM25Floor(fused, keywordDocs, fusedSnapshot, limit, BM25FloorMaxFilesFor(limit))
	stageLog = append(stageLog, "bm25_floor_reinserted", bm25Reinserted)
	observability.RecordBM25FloorReinserted(bm25Reinserted)
	timer.Mark("bm25_floor")

	// 13c. Phase 3 §D parent-child swap. After all ranking is settled,
	// swap each child row's Content + ContextualPrefix with the parent's
	// (small-to-big retrieval) AND collapse multiple children of the same
	// parent into one slot. Only fires on rows with non-nil ParentChunkID
	// — legacy flat rows pass through unchanged. When the chunkSvc
	// dependency wasn't wired (older call sites) the swap is a no-op;
	// rows with parent_chunk_id then surface their child content, which
	// is a soft degradation rather than a search-time error.
	parentSwapCount := 0
	parentLookupCount := 0
	parentDroppedCount := 0
	if s.chunkSvc != nil {
		parentIDs := collectParentIDs(fused)
		parentLookupCount = len(parentIDs)
		if len(parentIDs) > 0 {
			parents, perr := s.chunkSvc.LookupParentContent(ctx, parentIDs)
			if perr != nil {
				logctx.From(ctx).Warn("rag.search.parent_lookup_failed",
					"error", perr, "ids_count", len(parentIDs))
				observability.RecordParentSwap("lookup_failed", len(parentIDs))
			} else {
				fused, parentSwapCount, parentDroppedCount = swapToParents(fused, parents)
				observability.RecordParentSwap("swapped", parentSwapCount)
			}
		}
	}
	stageLog = append(stageLog,
		"parent_swap_count", parentSwapCount,
		"parent_lookups", parentLookupCount,
		"parent_dedup_dropped", parentDroppedCount,
	)
	timer.Mark("parent_swap")

	// Count how many final chunks carry a contextual prefix. If this is 0
	// for a KB whose admin panel says `contextual_enrichment=true`, the
	// files were ingested BEFORE enrichment was enabled and need to be
	// re-uploaded (or backfilled) before the prefix-aware LLM context
	// assembly can help.
	prefixCount := 0
	for _, d := range fused {
		if d.ContextualPrefix != "" {
			prefixCount++
		}
	}

	queryType := opts.QueryType
	if queryType == "" {
		queryType = QueryTypeUnknown
	}
	stageLog = append(stageLog,
		"final_docs", len(fused), "final_files", countFilesRanked(fused),
		"final_with_prefix", prefixCount,
		"limit", limit, "search_limit", searchLimit,
		"mmr_lambda", siteCfg.MMRLambda, "rerank_used", useReranker,
		"rerank_blend_alpha_global", siteCfg.RerankBlendAlpha,
		"min_sim_threshold", siteCfg.MinSimilarityThreshold,
		"score_drop_threshold", siteCfg.ScoreDropThreshold,
		"hnsw_ef_search", siteCfg.HNSWEfSearch,
		"query_type", queryType,
	)
	logctx.From(ctx).Info("rag.search.stages", stageLog...)

	chunks := make([]SearchChunk, len(fused))
	for i, doc := range fused {
		var meta map[string]any
		if len(doc.Metadata) > 0 {
			_ = json.Unmarshal(doc.Metadata, &meta)
		}
		if meta == nil {
			meta = map[string]any{}
		}
		chunks[i] = SearchChunk{
			ID:               doc.ID,
			Content:          doc.Content,
			ContextualPrefix: doc.ContextualPrefix,
			FileID:           doc.FileID,
			FileName:         fileNames[doc.FileID],
			Metadata:         meta,
			Score:            doc.Score,
			VectorScore:      doc.VectorScore,
			KeywordRank:      doc.KeywordRank,
			RerankScore:      doc.RerankScore,
			ParentChunkID:    doc.ParentChunkID,
			NodeKind:         doc.NodeKind,
			TreeLevel:        doc.TreeLevel,
		}
	}

	// ------------------------------------------------------------------
	// 14. CRAG-style relevance grading (optional, opt-in via opts.Grade)
	// ------------------------------------------------------------------
	graded := false
	relevantCount, ambiguousCount, irrelevantCount := 0, 0, 0
	if opts.Grade && len(chunks) > 0 {
		contents := make([]string, len(chunks))
		for i, c := range chunks {
			contents[i] = c.Content
		}
		gradeCtx, cancelGrade := context.WithTimeout(ctx, gradeRelevanceTimeout)
		grades, err := ai.GradeRelevance(gradeCtx, s.aiResolver, query, contents, kbID, opts.GraderModel)
		cancelGrade()
		// GradeRelevance fail-opens (nil error, right-length slice of
		// GradeAmbiguous) so this is defence-in-depth against a future
		// contract change: only mark `graded` when we actually got a
		// usable slice. A silent length mismatch would poison the
		// per-chunk Grade assignment below.
		if err == nil && len(grades) == len(chunks) {
			for i := range chunks {
				chunks[i].Grade = grades[i]
			}
			relevantCount, ambiguousCount, irrelevantCount = ai.CountByGrade(grades)
			graded = true
		}
	}

	// Distinct file IDs from the BM25 result, in BM25-rank order. Consumed
	// downstream by enumeration extraction to pre-seed the LLM candidate
	// list.
	var keywordFileIDs []string
	{
		seen := make(map[string]bool, len(keywordResults))
		for _, r := range keywordResults {
			if r.FileID == "" || seen[r.FileID] {
				continue
			}
			seen[r.FileID] = true
			keywordFileIDs = append(keywordFileIDs, r.FileID)
		}
	}

	result := &SearchResult{
		Chunks:              chunks,
		EnhancedQuery:       enhancedQuery,
		ContextWindowSize:   siteCfg.ContextWindowSize,
		TableName:           tableName,
		Graded:              graded,
		KeywordMatchFileIDs: keywordFileIDs,
	}
	logArgs := []any{
		"stage", "search",
		"query_len", len(query),
		"limit", limit,
		"search_limit", searchLimit,
		"chunks_returned", len(result.Chunks),
		"top_score", topScore(result.Chunks),
		"rerank_used", cfg.RerankModel != "",
		"duration_ms", time.Since(start).Milliseconds(),
	}
	if graded {
		logArgs = append(logArgs,
			"graded", true,
			"grade_relevant", relevantCount,
			"grade_ambiguous", ambiguousCount,
			"grade_irrelevant", irrelevantCount,
		)
	}
	logctx.From(ctx).Info("rag.search", logArgs...)
	span.SetAttributes(
		attribute.String("rag.kb_id", kbID),
		attribute.String("rag.language", lang),
		attribute.Int("rag.chunks_returned", len(result.Chunks)),
		attribute.Float64("rag.top_score", topScore(result.Chunks)),
		attribute.Bool("rag.rerank_used", cfg.RerankModel != ""),
		attribute.Float64("rag.mmr_lambda", siteCfg.MMRLambda),
	)
	observability.RecordSearch(lang, len(result.Chunks), topScore(result.Chunks), time.Since(start).Seconds())

	// Cache the assembled result for future semantic-similarity hits. The
	// QueryCache itself dispatches to a background writer (see StartWriter),
	// so Store is non-blocking; we still guard with the same enabled-check
	// used at lookup time so a runtime config flip doesn't poison the cache.
	if s.queryCache != nil && qcCfg.enabled && qcEmbedding != nil && qcHash != nil {
		if rj, mErr := json.Marshal(result); mErr == nil {
			_ = s.queryCache.Store(ctx, kbID, qcHash, qcEmbedding, query, rj, qcCfg.ttl)
		}
	}
	return result, nil
}

// ---------------------------------------------------------------------------
// runPrimarySearches — vector + keyword in parallel
// ---------------------------------------------------------------------------

func (s *SearchService) runPrimarySearches(
	ctx context.Context,
	tableName, embeddingJSON, query, kbID, pgConfig string,
	fileIDs []string,
	limit, dimensions int,
	useHalfvec bool,
	efSearch int,
	mrlTwoPass bool,
	embeddingLowJSON string,
	bm25SimpleArm, bm25TieredBoost bool,
	nodeKindFilter string,
) (vector []rawRow, keyword []rawRow, err error) {
	// Each goroutine below writes exactly one of these (vectorRows vs
	// keywordRows) and never the other, so the concurrent writes target
	// disjoint memory; g.Wait() establishes the happens-before before either
	// is read at the return. Race-free despite looking like shared state.
	var vectorRows, keywordRows []rawRow

	// Vector search is fatal on failure; keyword search is non-fatal (we
	// fall back to vector-only results). errgroup tracks only the fatal
	// error — the keyword goroutine swallows its own error so it doesn't
	// trip the group.
	g, gCtx := errgroup.WithContext(ctx)
	g.Go(func() (gErr error) {
		defer safego.RecoverError(&gErr)
		vectorRows, gErr = s.runVectorSearch(
			gCtx, tableName, embeddingJSON, kbID, fileIDs, limit, dimensions, useHalfvec, efSearch, mrlTwoPass, embeddingLowJSON, nodeKindFilter,
		)
		return gErr
	})
	g.Go(func() (gErr error) {
		defer safego.RecoverError(&gErr)
		rows, kErr := s.runKeywordSearch(
			gCtx, tableName, query, kbID, pgConfig, fileIDs, limit, bm25SimpleArm, bm25TieredBoost, nodeKindFilter,
		)
		if kErr != nil {
			// Non-fatal: leave keywordRows nil, do not propagate. Surface the
			// degradation so a sustained BM25 outage is visible in dashboards
			// even though hybrid search keeps returning results.
			observability.RecordKeywordSearchFailed("primary")
			logctx.From(gCtx).Warn("bm25 keyword search failed; degrading to vector-only",
				"kb_id", kbID, "error", kErr)
			return nil
		}
		keywordRows = rows
		return nil
	})

	if err := g.Wait(); err != nil {
		return nil, nil, fmt.Errorf("search: vector search: %w", err)
	}
	return vectorRows, keywordRows, nil
}

// ---------------------------------------------------------------------------
// runMultiQuerySearches — parallel extra vector searches
// ---------------------------------------------------------------------------

// multiQueryConcurrency caps the in-flight alt-query searches. altQueries
// can fan in from several sources at once (MultiQuery variants, StepBack,
// DecomposeRAG sub-questions), so under the heaviest config a single chat
// turn could otherwise launch ~10 simultaneous embedding+search goroutines;
// at 50 concurrent sessions that is ~500 goroutines hammering the embedding
// endpoint and connection pool. 5 mirrors multipassConcurrency's rationale
// (stay well under typical per-KB pool sizes) and still parallelises the
// common 3-4 alt-query case fully.
const multiQueryConcurrency = 5

func (s *SearchService) runMultiQuerySearches(
	ctx context.Context,
	tableName string,
	altQueries []string,
	kbID string,
	queryInstruction string,
	fileIDs []string,
	limit, dimensions int,
	useHalfvec bool,
	efSearch int,
	mrlTwoPass bool,
) [][]RankedDoc {
	type result struct {
		docs []RankedDoc
	}

	resultCh := make(chan result, len(altQueries))
	sem := make(chan struct{}, multiQueryConcurrency)
	var wg sync.WaitGroup

	for _, q := range altQueries {
		wg.Add(1)
		// safego.GoCtx provides panic recovery with request_id / user_id /
		// kb_id pulled from ctx in the recovered log line; wg.Done is the
		// goroutine's own defer so it fires before safego's recover and the
		// WaitGroup never hangs. On panic no result is sent on the channel —
		// that's safe because the drain loop below terminates on
		// `close(resultCh)` after `wg.Wait`, not on receiving exactly
		// `len(altQueries)` items.
		safego.GoCtx(ctx, func() {
			defer wg.Done()
			// Bound concurrency: acquire a slot inside the goroutine (not
			// around the spawn) so cancellation unblocks every pending
			// goroutine immediately. A cancelled goroutine sends nothing on
			// resultCh, which the close-driven drain loop tolerates.
			select {
			case sem <- struct{}{}:
			case <-ctx.Done():
				return
			}
			defer func() { <-sem }()
			embedCtx, cancelEmbed := context.WithTimeout(ctx, embedTimeout)
			emb, err := ai.EncodeQuery(embedCtx, s.aiResolver, q, queryInstruction, kbID, s.embeddingCache)
			cancelEmbed()
			if err != nil {
				// Multi-query is best-effort; failures degrade retrieval but
				// don't fail the parent search. Log so a flaky embedding
				// endpoint surfaces in observability instead of silently
				// trimming the candidate set.
				logctx.From(ctx).Warn("multi-query: embedding failed", "alt_query", q, "error", err)
				return
			}
			embStr := formatEmbedding(emb)
			var embLowStr string
			if mrlTwoPass {
				if low := L2NormalizeFirst256(emb); low != nil {
					embLowStr = formatEmbedding(low)
				}
			}
			rows, err := s.runVectorSearch(ctx, tableName, embStr, kbID, fileIDs, limit, dimensions, useHalfvec, efSearch, mrlTwoPass, embLowStr, "")
			if err != nil {
				logctx.From(ctx).Warn("multi-query: vector search failed", "alt_query", q, "error", err)
				return
			}
			resultCh <- result{docs: toRankedDocs(rows, true)}
		})
	}

	wg.Wait()
	close(resultCh)

	lists := make([][]RankedDoc, 0, len(altQueries))
	for r := range resultCh {
		if len(r.docs) > 0 {
			lists = append(lists, r.docs)
		}
	}
	return lists
}

// ---------------------------------------------------------------------------
// runMultiQueryBM25Searches — parallel extra keyword searches (P4 RAG-Fusion)
// ---------------------------------------------------------------------------

// runMultiQueryBM25Searches mirrors runMultiQuerySearches but runs
// the BM25 keyword arm per alt query instead of the vector arm.
// Each successful query yields one ranked list with toRankedDocs's
// keyword tagging (KeywordRank set, VectorScore=0). Empty / failed
// queries are dropped silently — RAG-Fusion is best-effort like
// the existing multi-query path.
//
// Used only when KBVectorConfig.RAGFusionEnabled is true. The cost
// is one BM25 query per alt phrasing (~1-5ms each), small relative
// to the vector arm.
func (s *SearchService) runMultiQueryBM25Searches(
	ctx context.Context,
	tableName string,
	altQueries []string,
	kbID, pgConfig string,
	fileIDs []string,
	limit int,
	simpleArm, tieredBoost bool,
) [][]RankedDoc {
	type result struct {
		docs []RankedDoc
	}

	resultCh := make(chan result, len(altQueries))
	sem := make(chan struct{}, multiQueryConcurrency)
	var wg sync.WaitGroup

	for _, q := range altQueries {
		wg.Add(1)
		// Same panic-recovery + drain + bounded-concurrency pattern as
		// runMultiQuerySearches.
		safego.GoCtx(ctx, func() {
			defer wg.Done()
			select {
			case sem <- struct{}{}:
			case <-ctx.Done():
				return
			}
			defer func() { <-sem }()
			rows, err := s.runKeywordSearch(ctx, tableName, q, kbID, pgConfig, fileIDs, limit, simpleArm, tieredBoost, "")
			if err != nil {
				observability.RecordKeywordSearchFailed("multi_query")
				logctx.From(ctx).Warn("multi-query bm25: keyword search failed", "alt_query", q, "error", err)
				return
			}
			if len(rows) == 0 {
				return
			}
			resultCh <- result{docs: toRankedDocs(rows, false)}
		})
	}

	wg.Wait()
	close(resultCh)

	lists := make([][]RankedDoc, 0, len(altQueries))
	for r := range resultCh {
		if len(r.docs) > 0 {
			lists = append(lists, r.docs)
		}
	}
	return lists
}

// ---------------------------------------------------------------------------
// rerank doc-string builder
// ---------------------------------------------------------------------------

// rerankDocBufPool recycles the []byte backing buffer used to concat each
// `contextual_prefix + "\n\n" + content` into a single string per doc inside
// the rerank loop. One buffer per Search call covers up to 25 docs; the
// per-doc `string(buf)` copy is unavoidable (the strings must be
// independent — the reranker may keep references) but the intermediate
// concat allocation goes away.
var rerankDocBufPool = sync.Pool{
	New: func() any { b := make([]byte, 0, 4096); return &b },
}

// searchScratch bundles the two transient maps Search builds on every call:
// the reranker index→score map and the post-dedup ID→doc snapshot the BM25
// floor reinserts from. Both are sized to the candidate-pool count (≈20–100)
// and were previously freshly allocated per search. Pooling keeps the bucket
// arrays warm across requests, matching bm25FloorScratchPool. clear() before
// each use drops stale entries while retaining the buckets; the snapshot is
// also cleared on return so an idle pooled entry doesn't pin RankedDoc content
// strings between searches (reinserted docs carry their own references, so the
// clear is safe).
type searchScratch struct {
	rerankScores map[int]float64
	snapshot     map[string]RankedDoc
}

var searchScratchPool = sync.Pool{
	New: func() any {
		return &searchScratch{
			rerankScores: make(map[int]float64, 64),
			snapshot:     make(map[string]RankedDoc, 64),
		}
	},
}

// buildRerankDocs returns one rerank-input string per doc. Docs with a
// non-empty ContextualPrefix get `prefix + "\n\n" + content`; bare-content
// docs pass through (no allocation when no prefix is set).
func buildRerankDocs(fused []RankedDoc) []string {
	docs := make([]string, len(fused))
	bufPtr := rerankDocBufPool.Get().(*[]byte)
	buf := (*bufPtr)[:0]
	for i, d := range fused {
		if d.ContextualPrefix == "" {
			docs[i] = d.Content
			continue
		}
		buf = append(buf[:0], d.ContextualPrefix...)
		buf = append(buf, "\n\n"...)
		buf = append(buf, d.Content...)
		docs[i] = string(buf)
	}
	*bufPtr = buf
	rerankDocBufPool.Put(bufPtr)
	return docs
}

// ---------------------------------------------------------------------------
// lookupFileNames — fetch file names from the main DB
// ---------------------------------------------------------------------------

func (s *SearchService) lookupFileNames(ctx context.Context, docs []RankedDoc) (map[string]string, error) {
	if len(docs) == 0 || s.mainDB == nil {
		return make(map[string]string), nil
	}

	// Collect unique file IDs.
	seen := make(map[string]struct{}, len(docs))
	ids := make([]string, 0, len(docs))
	for _, d := range docs {
		if d.FileID == "" {
			continue
		}
		if _, ok := seen[d.FileID]; !ok {
			seen[d.FileID] = struct{}{}
			ids = append(ids, d.FileID)
		}
	}
	if len(ids) == 0 {
		return make(map[string]string), nil
	}

	rows, err := s.mainDB.Query(ctx,
		`SELECT id::text, name FROM files WHERE id = ANY($1::uuid[])`,
		ids,
	)
	if err != nil {
		return nil, fmt.Errorf("lookup file names: %w", err)
	}
	defer rows.Close()

	names := make(map[string]string, len(ids))
	for rows.Next() {
		var id, name string
		if err := rows.Scan(&id, &name); err != nil {
			continue
		}
		names[id] = name
	}
	return names, rows.Err()
}

// ---------------------------------------------------------------------------
// fetchChunksByIDs — bulk chunk retrieval by primary key
// ---------------------------------------------------------------------------

// fetchChunksByIDs returns the chunks identified by `ids` from
// `tableName`, scoped to `kbID`. The returned rawRows carry Score=0
// since there's no ranking signal — the caller (search.go RRF
// stage) folds these into RRF as an extra list whose contribution
// comes from the rank position alone.
//
// Used by the AP-C4 graph-router chunk-injection path
// (SearchOptions.GraphChunkIDs). Empty / nil ids short-circuit
// without a DB round-trip. Table name is allowlist-validated against
// the same `validVectorTable` regex as FetchChunksByIndices because
// the name is interpolated unquoted into the SQL.
//
// Failure mode: any DB error is wrapped and returned. The chat-layer
// caller is responsible for fail-open (proceed without injection)
// rather than failing the chat turn — see PrepareChatContext.
func (s *SearchService) fetchChunksByIDs(ctx context.Context, tableName, kbID string, ids []string) ([]rawRow, error) {
	if len(ids) == 0 {
		return nil, nil
	}
	if !validVectorTable.MatchString(tableName) {
		return nil, fmt.Errorf("fetch chunks by ids: invalid table name %q", tableName)
	}
	// Build $3,$4,… placeholder list. args[0]=kbID, args[1..]=ids.
	args := make([]any, 0, 1+len(ids))
	args = append(args, kbID)
	var ph strings.Builder
	ph.Grow(len(ids) * 6)
	for i, id := range ids {
		args = append(args, id)
		if i > 0 {
			ph.WriteByte(',')
		}
		ph.WriteByte('$')
		ph.WriteString(strconv.Itoa(i + 2))
		ph.WriteString("::uuid")
	}
	sql := fmt.Sprintf(`
		SELECT id::text, content, COALESCE(contextual_prefix, ''), metadata::text, file_id::text, 0::float8 AS score,
		       COALESCE(parent_chunk_id::text, ''),
		       COALESCE(node_kind, 'leaf'),
		       COALESCE(tree_level, 0)
		FROM "%s"
		WHERE kb_id = $1::uuid AND id IN (%s)
	`, tableName, ph.String())
	rows, err := s.vectorDB.Query(ctx, sql, args...)
	if err != nil {
		return nil, fmt.Errorf("fetch chunks by ids: %w", err)
	}
	return collectRawRows(rows, len(ids))
}

// ---------------------------------------------------------------------------
// runHyPESearch — HyPE query-time arm
// ---------------------------------------------------------------------------

// runHyPESearch matches the query embedding against the HyPE question
// table, then maps the matched questions back to their PARENT chunks
// (returning real chunk content, never question text). Fails open to an
// empty list on any error — the chat turn must not fail because the HyPE
// arm hiccupped.
func (s *SearchService) runHyPESearch(ctx context.Context, tableName, embeddingStr, kbID string, fileIDs []string, limit, dimensions int) []RankedDoc {
	parentIDs, err := s.hype.Search(ctx, embeddingStr, kbID, fileIDs, limit, dimensions)
	if err != nil {
		logctx.From(ctx).Warn("rag.search.hype_failed", "error", err)
		return nil
	}
	if len(parentIDs) == 0 {
		return nil
	}
	rows, err := s.fetchChunksByIDs(ctx, tableName, kbID, parentIDs)
	if err != nil {
		logctx.From(ctx).Warn("rag.search.hype_parent_fetch_failed", "error", err, "requested", len(parentIDs))
		return nil
	}
	return toRankedDocs(rows, true)
}

// ---------------------------------------------------------------------------
// FetchChunksByIndices — neighbor chunk retrieval
// ---------------------------------------------------------------------------

// FetchChunksByIndices retrieves chunks from a specific file by their chunkIndex
// metadata values. This satisfies the NeighborFetcher interface and is used by
// ExpandNeighbors to fetch surrounding context.
func (s *SearchService) FetchChunksByIndices(ctx context.Context, tableName, kbID, fileID string, indices []int) ([]rawRow, error) {
	if len(indices) == 0 {
		return nil, nil
	}
	if !validVectorTable.MatchString(tableName) {
		return nil, fmt.Errorf("fetch neighbors: invalid table name %q", tableName)
	}
	// tableName is now whitelist-validated. Placeholders and the int indices
	// assembled below are fmt-safe because args carries the user data (kbID,
	// fileID) positionally.
	//
	// Placeholder list goes through a single strings.Builder + strconv.Itoa
	// rather than per-index fmt.Sprintf("$%d") — at neighbour fetches of
	// depth 5 in both directions we'd otherwise pay 10 short-string allocs
	// per call on an already-fast path.
	args := make([]any, 0, 2+len(indices))
	args = append(args, kbID, fileID)
	var ph strings.Builder
	ph.Grow(len(indices) * 5) // "$NN," per entry
	for i, idx := range indices {
		args = append(args, idx)
		if i > 0 {
			ph.WriteByte(',')
		}
		ph.WriteByte('$')
		ph.WriteString(strconv.Itoa(i + 3))
	}
	sql := fmt.Sprintf(`
		SELECT id::text, content, COALESCE(contextual_prefix, ''), metadata::text, file_id::text, 0::float8 AS score,
		       COALESCE(parent_chunk_id::text, ''),
		       COALESCE(node_kind, 'leaf'),
		       COALESCE(tree_level, 0)
		FROM "%s"
		WHERE kb_id = $1::uuid AND file_id = $2::uuid
		  AND (metadata::jsonb->>'chunkIndex')::int IN (%s)
	`, tableName, ph.String())
	rows, err := s.vectorDB.Query(ctx, sql, args...)
	if err != nil {
		return nil, fmt.Errorf("fetch neighbors: %w", err)
	}
	return collectRawRows(rows, len(indices))
}
