package ai

import (
	"testing"
)

// TestParseKGJSON_PlainAndWrapped: the LLM occasionally wraps its
// JSON in markdown (```json ... ```) or trailing prose. parseKGJSON
// tolerates both via the {-to-} extraction fallback. Keep both
// shapes parsing.
func TestParseKGJSON_PlainAndWrapped(t *testing.T) {
	t.Parallel()
	plain := `{"entities":[{"name":"PPM","type":"organization"}],"relations":[]}`
	got, err := parseKGJSON(plain)
	if err != nil {
		t.Fatalf("plain JSON failed: %v", err)
	}
	if len(got.Entities) != 1 || got.Entities[0].Name != "PPM" {
		t.Errorf("plain entities lost: %+v", got.Entities)
	}

	wrapped := "```json\n" + plain + "\n```\nGenerated by GPT."
	got, err = parseKGJSON(wrapped)
	if err != nil {
		t.Fatalf("wrapped JSON failed: %v", err)
	}
	if len(got.Entities) != 1 {
		t.Errorf("wrapped extraction failed: %+v", got)
	}
}

// TestParseKGJSON_Garbage: complete failure returns the error path.
// Important the error includes a snippet of the raw text so
// operators can debug LLM regressions from logs.
func TestParseKGJSON_Garbage(t *testing.T) {
	t.Parallel()
	_, err := parseKGJSON("definitely not json at all")
	if err == nil {
		t.Error("expected error for non-JSON input")
	}
}

// TestParseKGJSON_EmptyArrays: the prompt instructs the LLM to emit
// {"entities":[],"relations":[]} when a chunk has no entities. The
// parser must return cleanly with empty slices, NOT error — otherwise
// every entity-free chunk would cost an "error" metric and a log
// line.
func TestParseKGJSON_EmptyArrays(t *testing.T) {
	t.Parallel()
	empty := `{"entities":[],"relations":[]}`
	got, err := parseKGJSON(empty)
	if err != nil {
		t.Fatalf("empty arrays must parse cleanly: %v", err)
	}
	if got.Entities == nil {
		// Equality with nil is fine for an empty unmarshalled slice;
		// pin the documented behaviour: empty-not-error.
		t.Log("entities is nil for {entities:[]} — acceptable, empty case detected upstream by len()")
	}
	if len(got.Entities) != 0 || len(got.Relations) != 0 {
		t.Errorf("expected zero-len slices, got: %+v", got)
	}
}
